/* automatically generated from xfwm4-tweaks-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tweaks_dialog_glade)
#endif
#ifdef __GNUC__
static const char tweaks_dialog_glade[] __attribute__ ((__aligned__ (4))) =
#else
static const char tweaks_dialog_glade[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE"
  " glade-interface SYSTEM \"glade-2.0.dtd\">\n<!--Generated with glade3 3"
  ".4.5 on Sun Jun 29 23:59:48 2008 -->\n<glade-interface>\n  <requires li"
  "b=\"xfce4\"/>\n  <widget class=\"GtkDialog\" id=\"main-dialog\">\n    <"
  "property name=\"width_request\">500</property>\n    <property name=\"bo"
  "rder_width\">5</property>\n    <property name=\"window_position\">GTK_W"
  "IN_POS_CENTER_ON_PARENT</property>\n    <property name=\"type_hint\">GD"
  "K_WINDOW_TYPE_HINT_DIALOG</property>\n    <property name=\"has_separato"
  "r\">False</property>\n    <child internal-child=\"vbox\">\n      <widge"
  "t class=\"GtkVBox\" id=\"main-vbox\">\n        <property name=\"visible"
  "\">True</property>\n        <property name=\"spacing\">2</property>\n  "
  "      <child>\n          <widget class=\"XfceHeading\" id=\"xfce-headin"
  "g1\">\n            <property name=\"events\">GDK_POINTER_MOTION_MASK | "
  "GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n            <property name=\"icon_name\">wmtweaks</"
  "property>\n            <property name=\"title\" translatable=\"yes\">Wi"
  "ndow Manager Tweaks</property>\n          </widget>\n          <packing"
  ">\n            <property name=\"expand\">False</property>\n            "
  "<property name=\"fill\">False</property>\n            <property name=\""
  "position\">1</property>\n          </packing>\n        </child>\n      "
  "  <child>\n          <widget class=\"GtkNotebook\" id=\"notebook1\">\n "
  "           <property name=\"visible\">True</property>\n            <pro"
  "perty name=\"can_focus\">True</property>\n            <child>\n        "
  "      <widget class=\"GtkVBox\" id=\"vbox1\">\n                <propert"
  "y name=\"visible\">True</property>\n                <child>\n          "
  "        <widget class=\"GtkCheckButton\" id=\"cycle_minimum_check\">\n "
  "                   <property name=\"visible\">True</property>\n        "
  "            <property name=\"can_focus\">True</property>\n             "
  "       <property name=\"label\" translatable=\"yes\">Skip windows that "
  "have \"skip pager\"\nor \"skip taskbar\" properties set</property>\n   "
  "                 <property name=\"response_id\">0</property>\n         "
  "           <property name=\"draw_indicator\">True</property>\n         "
  "         </widget>\n                  <packing>\n                    <p"
  "roperty name=\"expand\">False</property>\n                    <property"
  " name=\"fill\">False</property>\n                  </packing>\n        "
  "        </child>\n                <child>\n                  <widget cl"
  "ass=\"GtkCheckButton\" id=\"cycle_hidden_check\">\n                    "
  "<property name=\"visible\">True</property>\n                    <proper"
  "ty name=\"can_focus\">True</property>\n                    <property na"
  "me=\"label\" translatable=\"yes\">Include hidden (i.e. iconified) windo"
  "ws</property>\n                    <property name=\"response_id\">0</pr"
  "operty>\n                    <property name=\"draw_indicator\">True</pr"
  "operty>\n                  </widget>\n                  <packing>\n    "
  "                <property name=\"expand\">False</property>\n           "
  "         <property name=\"fill\">False</property>\n                    "
  "<property name=\"position\">1</property>\n                  </packing>\n"
  "                </child>\n                <child>\n                  <w"
  "idget class=\"GtkCheckButton\" id=\"cycle_workspaces_check\">\n        "
  "            <property name=\"visible\">True</property>\n               "
  "     <property name=\"can_focus\">True</property>\n                    "
  "<property name=\"label\" translatable=\"yes\">Cycle through windows on "
  "all workspaces</property>\n                    <property name=\"respons"
  "e_id\">0</property>\n                    <property name=\"draw_indicato"
  "r\">True</property>\n                  </widget>\n                  <pa"
  "cking>\n                    <property name=\"expand\">False</property>\n"
  "                    <property name=\"fill\">False</property>\n         "
  "           <property name=\"position\">2</property>\n                  "
  "</packing>\n                </child>\n              </widget>\n        "
  "    </child>\n            <child>\n              <widget class=\"GtkLab"
  "el\" id=\"label1\">\n                <property name=\"visible\">True</p"
  "roperty>\n                <property name=\"label\" translatable=\"yes\""
  ">Cycling</property>\n              </widget>\n              <packing>\n"
  "                <property name=\"type\">tab</property>\n               "
  " <property name=\"tab_fill\">False</property>\n              </packing>"
  "\n            </child>\n            <child>\n              <widget clas"
  "s=\"GtkVBox\" id=\"vbox3\">\n                <property name=\"visible\""
  ">True</property>\n                <property name=\"spacing\">3</propert"
  "y>\n                <child>\n                  <widget class=\"GtkCheck"
  "Button\" id=\"prevent_focus_stealing_check\">\n                    <pro"
  "perty name=\"visible\">True</property>\n                    <property n"
  "ame=\"can_focus\">True</property>\n                    <property name=\""
  "label\" translatable=\"yes\">Activate focus stealing prevention</proper"
  "ty>\n                    <property name=\"response_id\">0</property>\n "
  "                   <property name=\"draw_indicator\">True</property>\n "
  "                 </widget>\n                  <packing>\n              "
  "      <property name=\"expand\">False</property>\n                    <"
  "property name=\"fill\">False</property>\n                  </packing>\n"
  "                </child>\n                <child>\n                  <w"
  "idget class=\"GtkCheckButton\" id=\"focus_hint_check\">\n              "
  "      <property name=\"visible\">True</property>\n                    <"
  "property name=\"can_focus\">True</property>\n                    <prope"
  "rty name=\"label\" translatable=\"yes\">Honor standard ICCCM focus hint"
  "</property>\n                    <property name=\"response_id\">0</prop"
  "erty>\n                    <property name=\"draw_indicator\">True</prop"
  "erty>\n                  </widget>\n                  <packing>\n      "
  "              <property name=\"expand\">False</property>\n             "
  "       <property name=\"fill\">False</property>\n                    <p"
  "roperty name=\"position\">1</property>\n                  </packing>\n "
  "               </child>\n                <child>\n                  <wi"
  "dget class=\"GtkVBox\" id=\"prevent_focus_stealing_box\">\n            "
  "        <property name=\"visible\">True</property>\n                   "
  " <property name=\"sensitive\">False</property>\n                    <ch"
  "ild>\n                      <widget class=\"GtkLabel\" id=\"label11\">\n"
  "                        <property name=\"visible\">True</property>\n   "
  "                     <property name=\"xalign\">0</property>\n          "
  "              <property name=\"label\" translatable=\"yes\">When a wind"
  "ow raises itself:</property>\n                      </widget>\n        "
  "            </child>\n                    <child>\n                    "
  "  <widget class=\"GtkAlignment\" id=\"alignment2\">\n                  "
  "      <property name=\"visible\">True</property>\n                     "
  "   <property name=\"left_padding\">12</property>\n                     "
  "   <child>\n                          <widget class=\"GtkVBox\" id=\"vb"
  "ox14\">\n                            <property name=\"visible\">True</p"
  "roperty>\n                            <child>\n                        "
  "      <widget class=\"GtkRadioButton\" id=\"activate_action_bring_optio"
  "n\">\n                                <property name=\"visible\">True</"
  "property>\n                                <property name=\"can_focus\""
  ">True</property>\n                                <property name=\"labe"
  "l\" translatable=\"yes\">Bring window on current workspace</property>\n"
  "                                <property name=\"response_id\">0</prope"
  "rty>\n                                <property name=\"active\">True</p"
  "roperty>\n                                <property name=\"draw_indicat"
  "or\">True</property>\n                              </widget>\n        "
  "                    </child>\n                            <child>\n    "
  "                          <widget class=\"GtkRadioButton\" id=\"activat"
  "e_action_switch_option\">\n                                <property na"
  "me=\"visible\">True</property>\n                                <proper"
  "ty name=\"can_focus\">True</property>\n                                "
  "<property name=\"label\" translatable=\"yes\">Switch to window\'s works"
  "pace</property>\n                                <property name=\"respo"
  "nse_id\">0</property>\n                                <property name=\""
  "active\">True</property>\n                                <property nam"
  "e=\"draw_indicator\">True</property>\n                                <"
  "property name=\"group\">activate_action_bring_option</property>\n      "
  "                        </widget>\n                              <packi"
  "ng>\n                                <property name=\"position\">1</pro"
  "perty>\n                              </packing>\n                     "
  "       </child>\n                            <child>\n                 "
  "             <widget class=\"GtkRadioButton\" id=\"activate_action_none"
  "_option\">\n                                <property name=\"visible\">"
  "True</property>\n                                <property name=\"can_f"
  "ocus\">True</property>\n                                <property name="
  "\"label\" translatable=\"yes\">Do nothing</property>\n                 "
  "               <property name=\"response_id\">0</property>\n           "
  "                     <property name=\"active\">True</property>\n       "
  "                         <property name=\"draw_indicator\">True</proper"
  "ty>\n                                <property name=\"group\">activate_"
  "action_bring_option</property>\n                              </widget>"
  "\n                              <packing>\n                            "
  "    <property name=\"position\">2</property>\n                         "
  "     </packing>\n                            </child>\n                "
  "          </widget>\n                        </child>\n                "
  "      </widget>\n                      <packing>\n                     "
  "   <property name=\"position\">1</property>\n                      </pa"
  "cking>\n                    </child>\n                  </widget>\n    "
  "              <packing>\n                    <property name=\"expand\">"
  "False</property>\n                    <property name=\"fill\">False</pr"
  "operty>\n                    <property name=\"position\">2</property>\n"
  "                  </packing>\n                </child>\n              <"
  "/widget>\n              <packing>\n                <property name=\"pos"
  "ition\">1</property>\n              </packing>\n            </child>\n "
  "           <child>\n              <widget class=\"GtkLabel\" id=\"label"
  "2\">\n                <property name=\"visible\">True</property>\n     "
  "           <property name=\"label\" translatable=\"yes\">Focus</propert"
  "y>\n              </widget>\n              <packing>\n                <"
  "property name=\"type\">tab</property>\n                <property name=\""
  "position\">1</property>\n                <property name=\"tab_fill\">Fa"
  "lse</property>\n              </packing>\n            </child>\n       "
  "     <child>\n              <widget class=\"GtkVBox\" id=\"vbox4\">\n  "
  "              <property name=\"visible\">True</property>\n             "
  "   <child>\n                  <widget class=\"GtkHBox\" id=\"hbox1\">\n"
  "                    <property name=\"visible\">True</property>\n       "
  "             <property name=\"spacing\">4</property>\n                 "
  "   <child>\n                      <widget class=\"GtkLabel\" id=\"label"
  "7\">\n                        <property name=\"visible\">True</property"
  ">\n                        <property name=\"xalign\">0</property>\n    "
  "                    <property name=\"label\" translatable=\"yes\">Key u"
  "sed to grab and move windows</property>\n                      </widget"
  ">\n                      <packing>\n                        <property n"
  "ame=\"expand\">False</property>\n                        <property name"
  "=\"fill\">False</property>\n                      </packing>\n         "
  "           </child>\n                    <child>\n                     "
  " <widget class=\"GtkComboBox\" id=\"easy_click_combo_box\">\n          "
  "              <property name=\"visible\">True</property>\n             "
  "           <property name=\"items\" translatable=\"yes\"></property>\n "
  "                     </widget>\n                      <packing>\n      "
  "                  <property name=\"expand\">False</property>\n         "
  "               <property name=\"fill\">False</property>\n              "
  "          <property name=\"position\">1</property>\n                   "
  "   </packing>\n                    </child>\n                  </widget"
  ">\n                  <packing>\n                    <property name=\"ex"
  "pand\">False</property>\n                    <property name=\"fill\">Fa"
  "lse</property>\n                  </packing>\n                </child>\n"
  "                <child>\n                  <widget class=\"GtkCheckButt"
  "on\" id=\"raise_on_click_check\">\n                    <property name=\""
  "visible\">True</property>\n                    <property name=\"can_foc"
  "us\">True</property>\n                    <property name=\"label\" tran"
  "slatable=\"yes\">Raise windows when any mouse button is pressed</proper"
  "ty>\n                    <property name=\"response_id\">0</property>\n "
  "                   <property name=\"draw_indicator\">True</property>\n "
  "                 </widget>\n                  <packing>\n              "
  "      <property name=\"expand\">False</property>\n                    <"
  "property name=\"fill\">False</property>\n                    <property "
  "name=\"position\">1</property>\n                  </packing>\n         "
  "       </child>\n                <child>\n                  <widget cla"
  "ss=\"GtkCheckButton\" id=\"borderless_maximize_check\">\n              "
  "      <property name=\"visible\">True</property>\n                    <"
  "property name=\"can_focus\">True</property>\n                    <prope"
  "rty name=\"label\" translatable=\"yes\">Hide frame of windows when maxi"
  "mized</property>\n                    <property name=\"response_id\">0<"
  "/property>\n                    <property name=\"draw_indicator\">True<"
  "/property>\n                  </widget>\n                  <packing>\n "
  "                   <property name=\"expand\">False</property>\n        "
  "            <property name=\"fill\">False</property>\n                 "
  "   <property name=\"position\">2</property>\n                  </packin"
  "g>\n                </child>\n                <child>\n                "
  "  <widget class=\"GtkCheckButton\" id=\"restore_on_move_check\">\n     "
  "               <property name=\"visible\">True</property>\n            "
  "        <property name=\"can_focus\">True</property>\n                 "
  "   <property name=\"label\" translatable=\"yes\">Restore original size "
  "of maximized windows when moving</property>\n                    <prope"
  "rty name=\"response_id\">0</property>\n                    <property na"
  "me=\"draw_indicator\">True</property>\n                  </widget>\n   "
  "               <packing>\n                    <property name=\"expand\""
  ">False</property>\n                    <property name=\"fill\">False</p"
  "roperty>\n                    <property name=\"position\">3</property>\n"
  "                  </packing>\n                </child>\n               "
  " <child>\n                  <widget class=\"GtkCheckButton\" id=\"snap_"
  "resist_check\">\n                    <property name=\"visible\">True</p"
  "roperty>\n                    <property name=\"can_focus\">True</proper"
  "ty>\n                    <property name=\"label\" translatable=\"yes\">"
  "Use edge resistance instead of window-snapping</property>\n            "
  "        <property name=\"response_id\">0</property>\n                  "
  "  <property name=\"draw_indicator\">True</property>\n                  "
  "</widget>\n                  <packing>\n                    <property n"
  "ame=\"expand\">False</property>\n                    <property name=\"f"
  "ill\">False</property>\n                    <property name=\"position\""
  ">4</property>\n                  </packing>\n                </child>\n"
  "              </widget>\n              <packing>\n                <prop"
  "erty name=\"position\">2</property>\n              </packing>\n        "
  "    </child>\n            <child>\n              <widget class=\"GtkLab"
  "el\" id=\"label3\">\n                <property name=\"visible\">True</p"
  "roperty>\n                <property name=\"label\" translatable=\"yes\""
  ">Accessibility</property>\n              </widget>\n              <pack"
  "ing>\n                <property name=\"type\">tab</property>\n         "
  "       <property name=\"position\">2</property>\n                <prope"
  "rty name=\"tab_fill\">False</property>\n              </packing>\n     "
  "       </child>\n            <child>\n              <widget class=\"Gtk"
  "VBox\" id=\"vbox5\">\n                <property name=\"visible\">True</"
  "property>\n                <child>\n                  <widget class=\"G"
  "tkCheckButton\" id=\"scroll_workspaces_check\">\n                    <p"
  "roperty name=\"visible\">True</property>\n                    <property"
  " name=\"can_focus\">True</property>\n                    <property name"
  "=\"label\" translatable=\"yes\">Switch workspaces using mousewheel over"
  " desktop</property>\n                    <property name=\"response_id\""
  ">0</property>\n                    <property name=\"draw_indicator\">Tr"
  "ue</property>\n                  </widget>\n                  <packing>"
  "\n                    <property name=\"expand\">False</property>\n     "
  "               <property name=\"fill\">False</property>\n              "
  "    </packing>\n                </child>\n                <child>\n    "
  "              <widget class=\"GtkCheckButton\" id=\"toggle_workspaces_c"
  "heck\">\n                    <property name=\"visible\">True</property>"
  "\n                    <property name=\"can_focus\">True</property>\n   "
  "                 <property name=\"label\" translatable=\"yes\">Remember"
  " and recall previous workspace\nwhen switching via keyboard shortcuts</"
  "property>\n                    <property name=\"response_id\">0</proper"
  "ty>\n                    <property name=\"draw_indicator\">True</proper"
  "ty>\n                  </widget>\n                  <packing>\n        "
  "            <property name=\"expand\">False</property>\n               "
  "     <property name=\"fill\">False</property>\n                    <pro"
  "perty name=\"position\">1</property>\n                  </packing>\n   "
  "             </child>\n                <child>\n                  <widg"
  "et class=\"GtkCheckButton\" id=\"wrap_layout_check\">\n                "
  "    <property name=\"visible\">True</property>\n                    <pr"
  "operty name=\"can_focus\">True</property>\n                    <propert"
  "y name=\"label\" translatable=\"yes\">Wrap workspaced depending on the "
  "actual desktop layout</property>\n                    <property name=\""
  "response_id\">0</property>\n                    <property name=\"draw_i"
  "ndicator\">True</property>\n                  </widget>\n              "
  "    <packing>\n                    <property name=\"expand\">False</pro"
  "perty>\n                    <property name=\"fill\">False</property>\n "
  "                   <property name=\"position\">2</property>\n          "
  "        </packing>\n                </child>\n                <child>\n"
  "                  <widget class=\"GtkCheckButton\" id=\"wrap_cycle_chec"
  "k\">\n                    <property name=\"visible\">True</property>\n "
  "                   <property name=\"can_focus\">True</property>\n      "
  "              <property name=\"label\" translatable=\"yes\">Wrap worksp"
  "aces when the first or the last workspace is reached</property>\n      "
  "              <property name=\"response_id\">0</property>\n            "
  "        <property name=\"draw_indicator\">True</property>\n            "
  "      </widget>\n                  <packing>\n                    <prop"
  "erty name=\"expand\">False</property>\n                    <property na"
  "me=\"fill\">False</property>\n                    <property name=\"posi"
  "tion\">3</property>\n                  </packing>\n                </ch"
  "ild>\n              </widget>\n              <packing>\n               "
  " <property name=\"position\">3</property>\n              </packing>\n  "
  "          </child>\n            <child>\n              <widget class=\""
  "GtkLabel\" id=\"label4\">\n                <property name=\"visible\">T"
  "rue</property>\n                <property name=\"label\" translatable=\""
  "yes\">Workspaces</property>\n              </widget>\n              <pa"
  "cking>\n                <property name=\"type\">tab</property>\n       "
  "         <property name=\"position\">3</property>\n                <pro"
  "perty name=\"tab_fill\">False</property>\n              </packing>\n   "
  "         </child>\n            <child>\n              <widget class=\"G"
  "tkVBox\" id=\"vbox6\">\n                <property name=\"visible\">True"
  "</property>\n                <child>\n                  <widget class=\""
  "GtkLabel\" id=\"label8\">\n                    <property name=\"visible"
  "\">True</property>\n                    <property name=\"xalign\">0</pr"
  "operty>\n                    <property name=\"label\" translatable=\"ye"
  "s\">Minimum size of windows to trigger smart placement</property>\n    "
  "              </widget>\n                  <packing>\n                 "
  "   <property name=\"expand\">False</property>\n                    <pro"
  "perty name=\"fill\">False</property>\n                  </packing>\n   "
  "             </child>\n                <child>\n                  <widg"
  "et class=\"GtkHBox\" id=\"hbox2\">\n                    <property name="
  "\"visible\">True</property>\n                    <child>\n             "
  "         <widget class=\"GtkLabel\" id=\"label9\">\n                   "
  "     <property name=\"visible\">True</property>\n                      "
  "  <property name=\"label\" translatable=\"yes\">Small</property>\n     "
  "                 </widget>\n                      <packing>\n          "
  "              <property name=\"expand\">False</property>\n             "
  "           <property name=\"fill\">False</property>\n                  "
  "    </packing>\n                    </child>\n                    <chil"
  "d>\n                      <widget class=\"GtkHScale\" id=\"placement_ra"
  "tio_scale\">\n                        <property name=\"visible\">True</"
  "property>\n                        <property name=\"can_focus\">True</p"
  "roperty>\n                        <property name=\"adjustment\">88 0 10"
  "0 1 10 10</property>\n                        <property name=\"restrict"
  "_to_fill_level\">False</property>\n                        <property na"
  "me=\"draw_value\">False</property>\n                      </widget>\n  "
  "                    <packing>\n                        <property name=\""
  "position\">1</property>\n                      </packing>\n            "
  "        </child>\n                    <child>\n                      <w"
  "idget class=\"GtkLabel\" id=\"label10\">\n                        <prop"
  "erty name=\"visible\">True</property>\n                        <propert"
  "y name=\"label\" translatable=\"yes\">Large</property>\n               "
  "       </widget>\n                      <packing>\n                    "
  "    <property name=\"expand\">False</property>\n                       "
  " <property name=\"position\">2</property>\n                      </pack"
  "ing>\n                    </child>\n                  </widget>\n      "
  "            <packing>\n                    <property name=\"expand\">Fa"
  "lse</property>\n                    <property name=\"fill\">False</prop"
  "erty>\n                    <property name=\"position\">1</property>\n  "
  "                </packing>\n                </child>\n              </w"
  "idget>\n              <packing>\n                <property name=\"posit"
  "ion\">4</property>\n              </packing>\n            </child>\n   "
  "         <child>\n              <widget class=\"GtkLabel\" id=\"label5\""
  ">\n                <property name=\"visible\">True</property>\n        "
  "        <property name=\"label\" translatable=\"yes\">Placement</proper"
  "ty>\n              </widget>\n              <packing>\n                "
  "<property name=\"type\">tab</property>\n                <property name="
  "\"position\">4</property>\n                <property name=\"tab_fill\">"
  "False</property>\n              </packing>\n            </child>\n     "
  "       <child>\n              <widget class=\"GtkVBox\" id=\"vbox7\">\n"
  "                <property name=\"visible\">True</property>\n           "
  "     <child>\n                  <widget class=\"GtkCheckButton\" id=\"u"
  "se_compositing_check\">\n                    <property name=\"visible\""
  ">True</property>\n                    <property name=\"can_focus\">True"
  "</property>\n                    <property name=\"label\" translatable="
  "\"yes\">Enable display compositing</property>\n                    <pro"
  "perty name=\"response_id\">0</property>\n                    <property "
  "name=\"draw_indicator\">True</property>\n                  </widget>\n "
  "                 <packing>\n                    <property name=\"expand"
  "\">False</property>\n                    <property name=\"fill\">False<"
  "/property>\n                  </packing>\n                </child>\n   "
  "             <child>\n                  <widget class=\"GtkScrolledWind"
  "ow\" id=\"use_compositing_box\">\n                    <property name=\""
  "visible\">True</property>\n                    <property name=\"sensiti"
  "ve\">False</property>\n                    <property name=\"can_focus\""
  ">True</property>\n                    <property name=\"hscrollbar_polic"
  "y\">GTK_POLICY_AUTOMATIC</property>\n                    <property name"
  "=\"vscrollbar_policy\">GTK_POLICY_AUTOMATIC</property>\n               "
  "     <property name=\"shadow_type\">GTK_SHADOW_IN</property>\n         "
  "           <child>\n                      <widget class=\"GtkViewport\""
  " id=\"viewport1\">\n                        <property name=\"visible\">"
  "True</property>\n                        <property name=\"resize_mode\""
  ">GTK_RESIZE_QUEUE</property>\n                        <property name=\""
  "shadow_type\">GTK_SHADOW_NONE</property>\n                        <chil"
  "d>\n                          <widget class=\"GtkAlignment\" id=\"align"
  "ment1\">\n                            <property name=\"visible\">True</"
  "property>\n                            <property name=\"left_padding\">"
  "10</property>\n                            <child>\n                   "
  "           <widget class=\"GtkVBox\" id=\"vbox8\">\n                   "
  "             <property name=\"visible\">True</property>\n              "
  "                  <property name=\"spacing\">3</property>\n            "
  "                    <child>\n                                  <widget "
  "class=\"GtkCheckButton\" id=\"unredirect_overlays_check\">\n           "
  "                         <property name=\"visible\">True</property>\n  "
  "                                  <property name=\"can_focus\">True</pr"
  "operty>\n                                    <property name=\"label\" t"
  "ranslatable=\"yes\">Display fullscreen overlay windows directly</proper"
  "ty>\n                                    <property name=\"response_id\""
  ">0</property>\n                                    <property name=\"dra"
  "w_indicator\">True</property>\n                                  </widg"
  "et>\n                                </child>\n                        "
  "        <child>\n                                  <widget class=\"GtkC"
  "heckButton\" id=\"show_frame_shadow_check\">\n                         "
  "           <property name=\"visible\">True</property>\n                "
  "                    <property name=\"can_focus\">True</property>\n     "
  "                               <property name=\"label\" translatable=\""
  "yes\">Show shadows under regular windows</property>\n                  "
  "                  <property name=\"response_id\">0</property>\n        "
  "                            <property name=\"draw_indicator\">True</pro"
  "perty>\n                                  </widget>\n                  "
  "                <packing>\n                                    <propert"
  "y name=\"position\">1</property>\n                                  </p"
  "acking>\n                                </child>\n                    "
  "            <child>\n                                  <widget class=\""
  "GtkCheckButton\" id=\"show_popup_shadow_check\">\n                     "
  "               <property name=\"visible\">True</property>\n            "
  "                        <property name=\"can_focus\">True</property>\n "
  "                                   <property name=\"label\" translatabl"
  "e=\"yes\">Show shadows under popup windows</property>\n                "
  "                    <property name=\"response_id\">0</property>\n      "
  "                              <property name=\"draw_indicator\">True</p"
  "roperty>\n                                  </widget>\n                "
  "                  <packing>\n                                    <prope"
  "rty name=\"position\">2</property>\n                                  <"
  "/packing>\n                                </child>\n                  "
  "              <child>\n                                  <widget class="
  "\"GtkCheckButton\" id=\"show_dock_shadow_check\">\n                    "
  "                <property name=\"visible\">True</property>\n           "
  "                         <property name=\"can_focus\">True</property>\n"
  "                                    <property name=\"label\" translatab"
  "le=\"yes\">Show shadows under docking windows</property>\n             "
  "                       <property name=\"response_id\">0</property>\n   "
  "                                 <property name=\"draw_indicator\">True"
  "</property>\n                                  </widget>\n             "
  "                     <packing>\n                                    <pr"
  "operty name=\"position\">3</property>\n                                "
  "  </packing>\n                                </child>\n               "
  "                 <child>\n                                  <widget cla"
  "ss=\"GtkVBox\" id=\"vbox9\">\n                                    <prop"
  "erty name=\"visible\">True</property>\n                                "
  "    <child>\n                                      <widget class=\"GtkL"
  "abel\" id=\"label12\">\n                                        <proper"
  "ty name=\"visible\">True</property>\n                                  "
  "      <property name=\"xalign\">0</property>\n                         "
  "               <property name=\"label\" translatable=\"yes\">Opacity of"
  " window decorations</property>\n                                      <"
  "/widget>\n                                      <packing>\n            "
  "                            <property name=\"expand\">False</property>\n"
  "                                      </packing>\n                     "
  "               </child>\n                                    <child>\n "
  "                                     <widget class=\"GtkHBox\" id=\"hbo"
  "x3\">\n                                        <property name=\"visible"
  "\">True</property>\n                                        <child>\n  "
  "                                        <widget class=\"GtkLabel\" id=\""
  "label17\">\n                                            <property name="
  "\"visible\">True</property>\n                                          "
  "  <property name=\"label\" translatable=\"yes\">&lt;i&gt;Transparent&lt"
  ";/i&gt;</property>\n                                            <proper"
  "ty name=\"use_markup\">True</property>\n                               "
  "           </widget>\n                                          <packin"
  "g>\n                                            <property name=\"expand"
  "\">False</property>\n                                            <prope"
  "rty name=\"fill\">False</property>\n                                   "
  "       </packing>\n                                        </child>\n  "
  "                                      <child>\n                        "
  "                  <widget class=\"GtkHScale\" id=\"frame_opacity_scale\""
  ">\n                                            <property name=\"visible"
  "\">True</property>\n                                            <proper"
  "ty name=\"can_focus\">True</property>\n                                "
  "            <property name=\"update_policy\">GTK_UPDATE_DISCONTINUOUS</"
  "property>\n                                            <property name=\""
  "adjustment\">90 0 100 1 10 0</property>\n                              "
  "              <property name=\"restrict_to_fill_level\">False</property"
  ">\n                                            <property name=\"draw_va"
  "lue\">False</property>\n                                          </wid"
  "get>\n                                          <packing>\n            "
  "                                <property name=\"position\">1</property"
  ">\n                                          </packing>\n              "
  "                          </child>\n                                   "
  "     <child>\n                                          <widget class=\""
  "GtkLabel\" id=\"label18\">\n                                           "
  " <property name=\"visible\">True</property>\n                          "
  "                  <property name=\"label\" translatable=\"yes\">&lt;i&g"
  "t;Opaque&lt;/i&gt;</property>\n                                        "
  "    <property name=\"use_markup\">True</property>\n                    "
  "                      </widget>\n                                      "
  "    <packing>\n                                            <property na"
  "me=\"expand\">False</property>\n                                       "
  "     <property name=\"fill\">False</property>\n                        "
  "                    <property name=\"position\">2</property>\n         "
  "                                 </packing>\n                          "
  "              </child>\n                                      </widget>"
  "\n                                      <packing>\n                    "
  "                    <property name=\"expand\">False</property>\n       "
  "                                 <property name=\"fill\">False</propert"
  "y>\n                                        <property name=\"position\""
  ">1</property>\n                                      </packing>\n      "
  "                              </child>\n                               "
  "   </widget>\n                                  <packing>\n            "
  "                        <property name=\"position\">4</property>\n     "
  "                             </packing>\n                              "
  "  </child>\n                                <child>\n                  "
  "                <widget class=\"GtkVBox\" id=\"vbox10\">\n             "
  "                       <property name=\"visible\">True</property>\n    "
  "                                <child>\n                              "
  "        <widget class=\"GtkLabel\" id=\"label13\">\n                   "
  "                     <property name=\"visible\">True</property>\n      "
  "                                  <property name=\"xalign\">0</property"
  ">\n                                        <property name=\"label\" tra"
  "nslatable=\"yes\">Opacity of inactive windows</property>\n             "
  "                         </widget>\n                                   "
  "   <packing>\n                                        <property name=\""
  "expand\">False</property>\n                                        <pro"
  "perty name=\"fill\">False</property>\n                                 "
  "     </packing>\n                                    </child>\n        "
  "                            <child>\n                                  "
  "    <widget class=\"GtkHBox\" id=\"hbox4\">\n                          "
  "              <property name=\"visible\">True</property>\n             "
  "                           <child>\n                                   "
  "       <widget class=\"GtkLabel\" id=\"label19\">\n                    "
  "                        <property name=\"visible\">True</property>\n   "
  "                                         <property name=\"label\" trans"
  "latable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</property>\n            "
  "                                <property name=\"use_markup\">True</pro"
  "perty>\n                                          </widget>\n          "
  "                                <packing>\n                            "
  "                <property name=\"expand\">False</property>\n           "
  "                                 <property name=\"fill\">False</propert"
  "y>\n                                          </packing>\n             "
  "                           </child>\n                                  "
  "      <child>\n                                          <widget class="
  "\"GtkHScale\" id=\"inactive_opacity_scale\">\n                         "
  "                   <property name=\"visible\">True</property>\n        "
  "                                    <property name=\"can_focus\">True</"
  "property>\n                                            <property name=\""
  "update_policy\">GTK_UPDATE_DISCONTINUOUS</property>\n                  "
  "                          <property name=\"adjustment\">90 0 100 1 10 0"
  "</property>\n                                            <property name"
  "=\"restrict_to_fill_level\">False</property>\n                         "
  "                   <property name=\"draw_value\">False</property>\n    "
  "                                      </widget>\n                      "
  "                    <packing>\n                                        "
  "    <property name=\"position\">1</property>\n                         "
  "                 </packing>\n                                        </"
  "child>\n                                        <child>\n              "
  "                            <widget class=\"GtkLabel\" id=\"label20\">\n"
  "                                            <property name=\"visible\">"
  "True</property>\n                                            <property "
  "name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property"
  ">\n                                            <property name=\"use_mar"
  "kup\">True</property>\n                                          </widg"
  "et>\n                                          <packing>\n             "
  "                               <property name=\"expand\">False</propert"
  "y>\n                                            <property name=\"fill\""
  ">False</property>\n                                            <propert"
  "y name=\"position\">2</property>\n                                     "
  "     </packing>\n                                        </child>\n    "
  "                                  </widget>\n                          "
  "            <packing>\n                                        <propert"
  "y name=\"expand\">False</property>\n                                   "
  "     <property name=\"fill\">False</property>\n                        "
  "                <property name=\"position\">1</property>\n             "
  "                         </packing>\n                                  "
  "  </child>\n                                  </widget>\n              "
  "                    <packing>\n                                    <pro"
  "perty name=\"position\">5</property>\n                                 "
  " </packing>\n                                </child>\n                "
  "                <child>\n                                  <widget clas"
  "s=\"GtkVBox\" id=\"vbox11\">\n                                    <prop"
  "erty name=\"visible\">True</property>\n                                "
  "    <child>\n                                      <widget class=\"GtkL"
  "abel\" id=\"label14\">\n                                        <proper"
  "ty name=\"visible\">True</property>\n                                  "
  "      <property name=\"xalign\">0</property>\n                         "
  "               <property name=\"label\" translatable=\"yes\">Opacity of"
  " windows during move</property>\n                                      "
  "</widget>\n                                      <packing>\n           "
  "                             <property name=\"expand\">False</property>"
  "\n                                        <property name=\"fill\">False"
  "</property>\n                                      </packing>\n        "
  "                            </child>\n                                 "
  "   <child>\n                                      <widget class=\"GtkHB"
  "ox\" id=\"hbox5\">\n                                        <property n"
  "ame=\"visible\">True</property>\n                                      "
  "  <child>\n                                          <widget class=\"Gt"
  "kLabel\" id=\"label21\">\n                                            <"
  "property name=\"visible\">True</property>\n                            "
  "                <property name=\"label\" translatable=\"yes\">&lt;i&gt;"
  "Transparent&lt;/i&gt;</property>\n                                     "
  "       <property name=\"use_markup\">True</property>\n                 "
  "                         </widget>\n                                   "
  "       <packing>\n                                            <property"
  " name=\"expand\">False</property>\n                                    "
  "        <property name=\"fill\">False</property>\n                     "
  "                     </packing>\n                                      "
  "  </child>\n                                        <child>\n          "
  "                                <widget class=\"GtkHScale\" id=\"move_o"
  "pacity_scale\">\n                                            <property "
  "name=\"visible\">True</property>\n                                     "
  "       <property name=\"can_focus\">True</property>\n                  "
  "                          <property name=\"update_policy\">GTK_UPDATE_D"
  "ISCONTINUOUS</property>\n                                            <p"
  "roperty name=\"adjustment\">100 0 100 1 10 0</property>\n              "
  "                              <property name=\"restrict_to_fill_level\""
  ">False</property>\n                                            <propert"
  "y name=\"draw_value\">False</property>\n                               "
  "           </widget>\n                                          <packin"
  "g>\n                                            <property name=\"positi"
  "on\">1</property>\n                                          </packing>"
  "\n                                        </child>\n                   "
  "                     <child>\n                                         "
  " <widget class=\"GtkLabel\" id=\"label22\">\n                          "
  "                  <property name=\"visible\">True</property>\n         "
  "                                   <property name=\"label\" translatabl"
  "e=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property>\n                       "
  "                     <property name=\"use_markup\">True</property>\n   "
  "                                       </widget>\n                     "
  "                     <packing>\n                                       "
  "     <property name=\"expand\">False</property>\n                      "
  "                      <property name=\"fill\">False</property>\n       "
  "                                     <property name=\"position\">2</pro"
  "perty>\n                                          </packing>\n         "
  "                               </child>\n                              "
  "        </widget>\n                                      <packing>\n   "
  "                                     <property name=\"expand\">False</p"
  "roperty>\n                                        <property name=\"fill"
  "\">False</property>\n                                        <property "
  "name=\"position\">1</property>\n                                      <"
  "/packing>\n                                    </child>\n              "
  "                    </widget>\n                                  <packi"
  "ng>\n                                    <property name=\"position\">6<"
  "/property>\n                                  </packing>\n             "
  "                   </child>\n                                <child>\n "
  "                                 <widget class=\"GtkVBox\" id=\"vbox12\""
  ">\n                                    <property name=\"visible\">True<"
  "/property>\n                                    <child>\n              "
  "                        <widget class=\"GtkLabel\" id=\"label15\">\n   "
  "                                     <property name=\"visible\">True</p"
  "roperty>\n                                        <property name=\"xali"
  "gn\">0</property>\n                                        <property na"
  "me=\"label\" translatable=\"yes\">Opacity of windows during resize</pro"
  "perty>\n                                      </widget>\n              "
  "                        <packing>\n                                    "
  "    <property name=\"expand\">False</property>\n                       "
  "                 <property name=\"fill\">False</property>\n            "
  "                          </packing>\n                                 "
  "   </child>\n                                    <child>\n             "
  "                         <widget class=\"GtkHBox\" id=\"hbox6\">\n     "
  "                                   <property name=\"visible\">True</pro"
  "perty>\n                                        <child>\n              "
  "                            <widget class=\"GtkLabel\" id=\"label23\">\n"
  "                                            <property name=\"visible\">"
  "True</property>\n                                            <property "
  "name=\"label\" translatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</pro"
  "perty>\n                                            <property name=\"us"
  "e_markup\">True</property>\n                                          <"
  "/widget>\n                                          <packing>\n        "
  "                                    <property name=\"expand\">False</pr"
  "operty>\n                                            <property name=\"f"
  "ill\">False</property>\n                                          </pac"
  "king>\n                                        </child>\n              "
  "                          <child>\n                                    "
  "      <widget class=\"GtkHScale\" id=\"resize_opacity_scale\">\n       "
  "                                     <property name=\"visible\">True</p"
  "roperty>\n                                            <property name=\""
  "can_focus\">True</property>\n                                          "
  "  <property name=\"update_policy\">GTK_UPDATE_DISCONTINUOUS</property>\n"
  "                                            <property name=\"adjustment"
  "\">90 0 100 1 10 0</property>\n                                        "
  "    <property name=\"restrict_to_fill_level\">False</property>\n       "
  "                                     <property name=\"draw_value\">Fals"
  "e</property>\n                                          </widget>\n    "
  "                                      <packing>\n                      "
  "                      <property name=\"position\">1</property>\n       "
  "                                   </packing>\n                        "
  "                </child>\n                                        <chil"
  "d>\n                                          <widget class=\"GtkLabel\""
  " id=\"label24\">\n                                            <property"
  " name=\"visible\">True</property>\n                                    "
  "        <property name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&l"
  "t;/i&gt;</property>\n                                            <prope"
  "rty name=\"use_markup\">True</property>\n                              "
  "            </widget>\n                                          <packi"
  "ng>\n                                            <property name=\"expan"
  "d\">False</property>\n                                            <prop"
  "erty name=\"fill\">False</property>\n                                  "
  "          <property name=\"position\">2</property>\n                   "
  "                       </packing>\n                                    "
  "    </child>\n                                      </widget>\n        "
  "                              <packing>\n                              "
  "          <property name=\"expand\">False</property>\n                 "
  "                       <property name=\"fill\">False</property>\n      "
  "                                  <property name=\"position\">1</proper"
  "ty>\n                                      </packing>\n                "
  "                    </child>\n                                  </widge"
  "t>\n                                  <packing>\n                      "
  "              <property name=\"position\">7</property>\n               "
  "                   </packing>\n                                </child>"
  "\n                                <child>\n                            "
  "      <widget class=\"GtkVBox\" id=\"vbox13\">\n                       "
  "             <property name=\"visible\">True</property>\n              "
  "                      <child>\n                                      <w"
  "idget class=\"GtkLabel\" id=\"label16\">\n                             "
  "           <property name=\"visible\">True</property>\n                "
  "                        <property name=\"xalign\">0</property>\n       "
  "                                 <property name=\"label\" translatable="
  "\"yes\">Opacity of popup windows</property>\n                          "
  "            </widget>\n                                      <packing>\n"
  "                                        <property name=\"expand\">False"
  "</property>\n                                        <property name=\"f"
  "ill\">False</property>\n                                      </packing"
  ">\n                                    </child>\n                      "
  "              <child>\n                                      <widget cl"
  "ass=\"GtkHBox\" id=\"hbox7\">\n                                        "
  "<property name=\"visible\">True</property>\n                           "
  "             <child>\n                                          <widget"
  " class=\"GtkLabel\" id=\"label25\">\n                                  "
  "          <property name=\"visible\">True</property>\n                 "
  "                           <property name=\"label\" translatable=\"yes\""
  ">&lt;i&gt;Transparent&lt;/i&gt;</property>\n                           "
  "                 <property name=\"use_markup\">True</property>\n       "
  "                                   </widget>\n                         "
  "                 <packing>\n                                           "
  " <property name=\"expand\">False</property>\n                          "
  "                  <property name=\"fill\">False</property>\n           "
  "                               </packing>\n                            "
  "            </child>\n                                        <child>\n"
  "                                          <widget class=\"GtkHScale\" i"
  "d=\"popup_opacity_scale\">\n                                           "
  " <property name=\"visible\">True</property>\n                          "
  "                  <property name=\"can_focus\">True</property>\n       "
  "                                     <property name=\"update_policy\">G"
  "TK_UPDATE_DISCONTINUOUS</property>\n                                   "
  "         <property name=\"adjustment\">90 0 100 1 10 0</property>\n    "
  "                                        <property name=\"restrict_to_fi"
  "ll_level\">False</property>\n                                          "
  "  <property name=\"draw_value\">False</property>\n                     "
  "                     </widget>\n                                       "
  "   <packing>\n                                            <property nam"
  "e=\"position\">1</property>\n                                          "
  "</packing>\n                                        </child>\n         "
  "                               <child>\n                               "
  "           <widget class=\"GtkLabel\" id=\"label26\">\n                "
  "                            <property name=\"visible\">True</property>\n"
  "                                            <property name=\"label\" tr"
  "anslatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property>\n              "
  "                              <property name=\"use_markup\">True</prope"
  "rty>\n                                          </widget>\n            "
  "                              <packing>\n                              "
  "              <property name=\"expand\">False</property>\n             "
  "                               <property name=\"fill\">False</property>"
  "\n                                            <property name=\"position"
  "\">2</property>\n                                          </packing>\n"
  "                                        </child>\n                     "
  "                 </widget>\n                                      <pack"
  "ing>\n                                        <property name=\"expand\""
  ">False</property>\n                                        <property na"
  "me=\"fill\">False</property>\n                                        <"
  "property name=\"position\">1</property>\n                              "
  "        </packing>\n                                    </child>\n     "
  "                             </widget>\n                               "
  "   <packing>\n                                    <property name=\"posi"
  "tion\">8</property>\n                                  </packing>\n    "
  "                            </child>\n                              </w"
  "idget>\n                            </child>\n                         "
  " </widget>\n                        </child>\n                      </w"
  "idget>\n                    </child>\n                  </widget>\n    "
  "              <packing>\n                    <property name=\"position\""
  ">1</property>\n                  </packing>\n                </child>\n"
  "              </widget>\n              <packing>\n                <prop"
  "erty name=\"position\">5</property>\n              </packing>\n        "
  "    </child>\n            <child>\n              <widget class=\"GtkLab"
  "el\" id=\"label6\">\n                <property name=\"visible\">True</p"
  "roperty>\n                <property name=\"label\" translatable=\"yes\""
  ">Compositor</property>\n              </widget>\n              <packing"
  ">\n                <property name=\"type\">tab</property>\n            "
  "    <property name=\"position\">5</property>\n                <property"
  " name=\"tab_fill\">False</property>\n              </packing>\n        "
  "    </child>\n          </widget>\n          <packing>\n            <pr"
  "operty name=\"position\">2</property>\n          </packing>\n        </"
  "child>\n        <child internal-child=\"action_area\">\n          <widg"
  "et class=\"GtkHButtonBox\" id=\"dialog-action_area1\">\n            <pr"
  "operty name=\"visible\">True</property>\n            <property name=\"l"
  "ayout_style\">GTK_BUTTONBOX_EDGE</property>\n            <child>\n     "
  "         <widget class=\"GtkButton\" id=\"button2\">\n                <"
  "property name=\"visible\">True</property>\n                <property na"
  "me=\"can_focus\">True</property>\n                <property name=\"rece"
  "ives_default\">True</property>\n                <property name=\"label\""
  " translatable=\"yes\">gtk-help</property>\n                <property na"
  "me=\"use_stock\">True</property>\n                <property name=\"resp"
  "onse_id\">0</property>\n              </widget>\n            </child>\n"
  "            <child>\n              <widget class=\"GtkButton\" id=\"but"
  "ton1\">\n                <property name=\"visible\">True</property>\n  "
  "              <property name=\"can_focus\">True</property>\n           "
  "     <property name=\"receives_default\">True</property>\n             "
  "   <property name=\"label\" translatable=\"yes\">gtk-close</property>\n"
  "                <property name=\"use_stock\">True</property>\n         "
  "       <property name=\"response_id\">0</property>\n              </wid"
  "get>\n              <packing>\n                <property name=\"positio"
  "n\">1</property>\n              </packing>\n            </child>\n     "
  "     </widget>\n          <packing>\n            <property name=\"expan"
  "d\">False</property>\n            <property name=\"pack_type\">GTK_PACK"
  "_END</property>\n          </packing>\n        </child>\n      </widget"
  ">\n    </child>\n  </widget>\n</glade-interface>\n"
};

static const unsigned tweaks_dialog_glade_length = 53689u;

