/* automatically generated from xfwm4-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfwm4_dialog_glade)
#endif
#ifdef __GNUC__
static const char xfwm4_dialog_glade[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfwm4_dialog_glade[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE"
  " glade-interface SYSTEM \"glade-2.0.dtd\">\n<!--Generated with glade3 3"
  ".4.5 on Sat Jul  5 12:39:55 2008 -->\n<glade-interface>\n  <requires li"
  "b=\"xfce4\"/>\n  <widget class=\"GtkDialog\" id=\"main-dialog\">\n    <"
  "property name=\"border_width\">5</property>\n    <property name=\"windo"
  "w_position\">GTK_WIN_POS_CENTER_ON_PARENT</property>\n    <property nam"
  "e=\"type_hint\">GDK_WINDOW_TYPE_HINT_DIALOG</property>\n    <property n"
  "ame=\"has_separator\">False</property>\n    <child internal-child=\"vbo"
  "x\">\n      <widget class=\"GtkVBox\" id=\"main-vbox\">\n        <prope"
  "rty name=\"visible\">True</property>\n        <property name=\"spacing\""
  ">2</property>\n        <child>\n          <widget class=\"XfceHeading\""
  " id=\"xfce-heading1\">\n            <property name=\"visible\">True</pr"
  "operty>\n            <property name=\"icon_name\">xfwm4</property>\n   "
  "         <property name=\"title\" translatable=\"yes\">Windowmanager Se"
  "ttings</property>\n          </widget>\n          <packing>\n          "
  "  <property name=\"expand\">False</property>\n            <property nam"
  "e=\"fill\">False</property>\n            <property name=\"position\">1<"
  "/property>\n          </packing>\n        </child>\n        <child>\n  "
  "        <widget class=\"GtkNotebook\" id=\"notebook1\">\n            <p"
  "roperty name=\"visible\">True</property>\n            <property name=\""
  "can_focus\">True</property>\n            <child>\n              <widget"
  " class=\"GtkAlignment\" id=\"alignment13\">\n                <property "
  "name=\"visible\">True</property>\n                <property name=\"top_"
  "padding\">4</property>\n                <property name=\"bottom_padding"
  "\">4</property>\n                <property name=\"left_padding\">4</pro"
  "perty>\n                <property name=\"right_padding\">4</property>\n"
  "                <child>\n                  <widget class=\"GtkHBox\" id"
  "=\"hbox7\">\n                    <property name=\"visible\">True</prope"
  "rty>\n                    <child>\n                      <widget class="
  "\"GtkScrolledWindow\" id=\"scrolledwindow3\">\n                        "
  "<property name=\"width_request\">120</property>\n                      "
  "  <property name=\"visible\">True</property>\n                        <"
  "property name=\"can_focus\">True</property>\n                        <p"
  "roperty name=\"hscrollbar_policy\">GTK_POLICY_AUTOMATIC</property>\n   "
  "                     <property name=\"vscrollbar_policy\">GTK_POLICY_AU"
  "TOMATIC</property>\n                        <property name=\"shadow_typ"
  "e\">GTK_SHADOW_IN</property>\n                        <child>\n        "
  "                  <widget class=\"GtkTreeView\" id=\"theme_name_treevie"
  "w\">\n                            <property name=\"visible\">True</prop"
  "erty>\n                            <property name=\"can_focus\">True</p"
  "roperty>\n                            <property name=\"headers_visible\""
  ">False</property>\n                          </widget>\n               "
  "         </child>\n                      </widget>\n                   "
  "   <packing>\n                        <property name=\"expand\">False</"
  "property>\n                        <property name=\"fill\">False</prope"
  "rty>\n                      </packing>\n                    </child>\n "
  "                   <child>\n                      <widget class=\"GtkVB"
  "ox\" id=\"vbox12\">\n                        <property name=\"visible\""
  ">True</property>\n                        <property name=\"spacing\">4<"
  "/property>\n                        <child>\n                          "
  "<widget class=\"GtkFrame\" id=\"frame10\">\n                           "
  " <property name=\"visible\">True</property>\n                          "
  "  <property name=\"label_xalign\">0</property>\n                       "
  "     <property name=\"shadow_type\">GTK_SHADOW_NONE</property>\n       "
  "                     <child>\n                              <widget cla"
  "ss=\"GtkAlignment\" id=\"alignment14\">\n                              "
  "  <property name=\"visible\">True</property>\n                         "
  "       <property name=\"left_padding\">12</property>\n                 "
  "               <property name=\"right_padding\">12</property>\n        "
  "                        <child>\n                                  <wid"
  "get class=\"GtkFontButton\" id=\"title_font_button\">\n                "
  "                    <property name=\"visible\">True</property>\n       "
  "                             <property name=\"can_focus\">True</propert"
  "y>\n                                    <property name=\"receives_defau"
  "lt\">True</property>\n                                    <property nam"
  "e=\"response_id\">0</property>\n                                  </wid"
  "get>\n                                </child>\n                       "
  "       </widget>\n                            </child>\n               "
  "             <child>\n                              <widget class=\"Gtk"
  "Label\" id=\"label23\">\n                                <property name"
  "=\"visible\">True</property>\n                                <property"
  " name=\"label\" translatable=\"yes\">&lt;b&gt;Title font&lt;/b&gt;</pro"
  "perty>\n                                <property name=\"use_markup\">T"
  "rue</property>\n                              </widget>\n              "
  "                <packing>\n                                <property na"
  "me=\"type\">label_item</property>\n                              </pack"
  "ing>\n                            </child>\n                          <"
  "/widget>\n                          <packing>\n                        "
  "    <property name=\"expand\">False</property>\n                       "
  "     <property name=\"fill\">False</property>\n                        "
  "  </packing>\n                        </child>\n                       "
  " <child>\n                          <widget class=\"GtkFrame\" id=\"fra"
  "me11\">\n                            <property name=\"visible\">True</p"
  "roperty>\n                            <property name=\"label_xalign\">0"
  "</property>\n                            <property name=\"shadow_type\""
  ">GTK_SHADOW_NONE</property>\n                            <child>\n     "
  "                         <widget class=\"GtkAlignment\" id=\"alignment1"
  "5\">\n                                <property name=\"visible\">True</"
  "property>\n                                <property name=\"left_paddin"
  "g\">12</property>\n                                <property name=\"rig"
  "ht_padding\">12</property>\n                                <child>\n  "
  "                                <widget class=\"GtkComboBox\" id=\"titl"
  "e_align_combo\">\n                                    <property name=\""
  "visible\">True</property>\n                                    <propert"
  "y name=\"items\" translatable=\"yes\"></property>\n                    "
  "              </widget>\n                                </child>\n    "
  "                          </widget>\n                            </chil"
  "d>\n                            <child>\n                              "
  "<widget class=\"GtkLabel\" id=\"label24\">\n                           "
  "     <property name=\"visible\">True</property>\n                      "
  "          <property name=\"label\" translatable=\"yes\">&lt;b&gt;Title "
  "alignment&lt;/b&gt;</property>\n                                <proper"
  "ty name=\"use_markup\">True</property>\n                              <"
  "/widget>\n                              <packing>\n                    "
  "            <property name=\"type\">label_item</property>\n            "
  "                  </packing>\n                            </child>\n   "
  "                       </widget>\n                          <packing>\n"
  "                            <property name=\"expand\">False</property>\n"
  "                            <property name=\"fill\">False</property>\n "
  "                           <property name=\"position\">1</property>\n  "
  "                        </packing>\n                        </child>\n "
  "                       <child>\n                          <widget class"
  "=\"GtkFrame\" id=\"frame12\">\n                            <property na"
  "me=\"visible\">True</property>\n                            <property n"
  "ame=\"label_xalign\">0</property>\n                            <propert"
  "y name=\"shadow_type\">GTK_SHADOW_NONE</property>\n                    "
  "        <child>\n                              <widget class=\"GtkAlign"
  "ment\" id=\"alignment16\">\n                                <property n"
  "ame=\"visible\">True</property>\n                                <prope"
  "rty name=\"left_padding\">12</property>\n                              "
  "  <property name=\"right_padding\">12</property>\n                     "
  "           <child>\n                                  <widget class=\"G"
  "tkVBox\" id=\"vbox13\">\n                                    <property "
  "name=\"visible\">True</property>\n                                    <"
  "child>\n                                      <widget class=\"GtkLabel\""
  " id=\"label26\">\n                                        <property nam"
  "e=\"visible\">True</property>\n                                        "
  "<property name=\"label\" translatable=\"yes\">Click and drag the button"
  "s to change the layout</property>\n                                    "
  "  </widget>\n                                    </child>\n            "
  "                        <child>\n                                      "
  "<widget class=\"GtkFrame\" id=\"active-frame\">\n                      "
  "                  <property name=\"visible\">True</property>\n         "
  "                               <property name=\"label_xalign\">0</prope"
  "rty>\n                                        <property name=\"shadow_t"
  "ype\">GTK_SHADOW_IN</property>\n                                       "
  " <child>\n                                          <widget class=\"Gtk"
  "Alignment\" id=\"alignment17\">\n                                      "
  "      <property name=\"visible\">True</property>\n                     "
  "                       <property name=\"bottom_padding\">4</property>\n"
  "                                            <property name=\"left_paddi"
  "ng\">4</property>\n                                            <propert"
  "y name=\"right_padding\">4</property>\n                                "
  "            <child>\n                                              <wid"
  "get class=\"GtkHBox\" id=\"active-box\">\n                             "
  "                   <property name=\"height_request\">26</property>\n   "
  "                                             <property name=\"visible\""
  ">True</property>\n                                                <chil"
  "d>\n                                                  <widget class=\"G"
  "tkButton\" id=\"button-layout-|\">\n                                   "
  "                 <property name=\"visible\">True</property>\n          "
  "                                          <property name=\"can_focus\">"
  "True</property>\n                                                    <p"
  "roperty name=\"receives_default\">True</property>\n                    "
  "                                <property name=\"tooltip\" translatable"
  "=\"yes\">The window title, it cannot be removed</property>\n           "
  "                                         <property name=\"label\" trans"
  "latable=\"yes\">Title</property>\n                                     "
  "               <property name=\"response_id\">0</property>\n           "
  "                                       </widget>\n                     "
  "                           </child>\n                                  "
  "            </widget>\n                                            </ch"
  "ild>\n                                          </widget>\n            "
  "                            </child>\n                                 "
  "       <child>\n                                          <widget class"
  "=\"GtkLabel\" id=\"label27\">\n                                        "
  "    <property name=\"visible\">True</property>\n                       "
  "                     <property name=\"label\" translatable=\"yes\">Acti"
  "ve</property>\n                                            <property na"
  "me=\"use_markup\">True</property>\n                                    "
  "      </widget>\n                                          <packing>\n "
  "                                           <property name=\"type\">labe"
  "l_item</property>\n                                          </packing>"
  "\n                                        </child>\n                   "
  "                   </widget>\n                                      <pa"
  "cking>\n                                        <property name=\"positi"
  "on\">1</property>\n                                      </packing>\n  "
  "                                  </child>\n                           "
  "         <child>\n                                      <widget class=\""
  "GtkFrame\" id=\"hidden-frame\">\n                                      "
  "  <property name=\"label_xalign\">0</property>\n                       "
  "                 <property name=\"shadow_type\">GTK_SHADOW_IN</property"
  ">\n                                        <child>\n                   "
  "                       <widget class=\"GtkAlignment\" id=\"alignment18\""
  ">\n                                            <property name=\"visible"
  "\">True</property>\n                                            <proper"
  "ty name=\"bottom_padding\">4</property>\n                              "
  "              <property name=\"left_padding\">4</property>\n           "
  "                                 <property name=\"right_padding\">4</pr"
  "operty>\n                                            <child>\n         "
  "                                     <widget class=\"GtkHBox\" id=\"hid"
  "den-box\">\n                                                <property n"
  "ame=\"height_request\">26</property>\n                                 "
  "               <property name=\"visible\">True</property>\n            "
  "                                    <property name=\"spacing\">5</prope"
  "rty>\n                                                <child>\n        "
  "                                          <widget class=\"GtkButton\" i"
  "d=\"button-layout-O\">\n                                               "
  "     <property name=\"visible\">True</property>\n                      "
  "                              <property name=\"can_focus\">True</proper"
  "ty>\n                                                    <property name"
  "=\"receives_default\">True</property>\n                                "
  "                    <property name=\"tooltip\" translatable=\"yes\">Men"
  "u</property>\n                                                    <prop"
  "erty name=\"response_id\">0</property>\n                               "
  "                     <child>\n                                         "
  "             <widget class=\"GtkImage\" id=\"image1\">\n               "
  "                                         <property name=\"visible\">Tru"
  "e</property>\n                                                        <"
  "property name=\"stock\">gtk-index</property>\n                         "
  "                             </widget>\n                               "
  "                     </child>\n                                        "
  "          </widget>\n                                                  "
  "<packing>\n                                                    <propert"
  "y name=\"expand\">False</property>\n                                   "
  "                 <property name=\"fill\">False</property>\n            "
  "                                      </packing>\n                     "
  "                           </child>\n                                  "
  "              <child>\n                                                "
  "  <widget class=\"GtkButton\" id=\"button-layout-T\">\n                "
  "                                    <property name=\"visible\">True</pr"
  "operty>\n                                                    <property "
  "name=\"can_focus\">True</property>\n                                   "
  "                 <property name=\"receives_default\">True</property>\n "
  "                                                   <property name=\"too"
  "ltip\" translatable=\"yes\">Stick</property>\n                         "
  "                           <property name=\"response_id\">0</property>\n"
  "                                                    <child>\n          "
  "                                            <widget class=\"GtkImage\" "
  "id=\"image2\">\n                                                       "
  " <property name=\"visible\">True</property>\n                          "
  "                              <property name=\"stock\">gtk-add</propert"
  "y>\n                                                      </widget>\n  "
  "                                                  </child>\n           "
  "                                       </widget>\n                     "
  "                             <packing>\n                               "
  "                     <property name=\"expand\">False</property>\n      "
  "                                              <property name=\"fill\">F"
  "alse</property>\n                                                    <p"
  "roperty name=\"position\">1</property>\n                               "
  "                   </packing>\n                                        "
  "        </child>\n                                                <chil"
  "d>\n                                                  <widget class=\"G"
  "tkButton\" id=\"button-layout-S\">\n                                   "
  "                 <property name=\"visible\">True</property>\n          "
  "                                          <property name=\"can_focus\">"
  "True</property>\n                                                    <p"
  "roperty name=\"receives_default\">True</property>\n                    "
  "                                <property name=\"tooltip\" translatable"
  "=\"yes\">Shade</property>\n                                            "
  "        <property name=\"response_id\">0</property>\n                  "
  "                                  <child>\n                            "
  "                          <widget class=\"GtkImage\" id=\"image3\">\n  "
  "                                                      <property name=\""
  "visible\">True</property>\n                                            "
  "            <property name=\"stock\">gtk-goto-top</property>\n         "
  "                                             </widget>\n               "
  "                                     </child>\n                        "
  "                          </widget>\n                                  "
  "                <packing>\n                                            "
  "        <property name=\"expand\">False</property>\n                   "
  "                                 <property name=\"fill\">False</propert"
  "y>\n                                                    <property name="
  "\"position\">2</property>\n                                            "
  "      </packing>\n                                                </chi"
  "ld>\n                                                <child>\n         "
  "                                         <widget class=\"GtkButton\" id"
  "=\"button-layout-H\">\n                                                "
  "    <property name=\"visible\">True</property>\n                       "
  "                             <property name=\"can_focus\">True</propert"
  "y>\n                                                    <property name="
  "\"receives_default\">True</property>\n                                 "
  "                   <property name=\"tooltip\" translatable=\"yes\">Hide"
  "</property>\n                                                    <prope"
  "rty name=\"response_id\">0</property>\n                                "
  "                    <child>\n                                          "
  "            <widget class=\"GtkImage\" id=\"image4\">\n                "
  "                                        <property name=\"visible\">True"
  "</property>\n                                                        <p"
  "roperty name=\"stock\">gtk-undo</property>\n                           "
  "                           </widget>\n                                 "
  "                   </child>\n                                          "
  "        </widget>\n                                                  <p"
  "acking>\n                                                    <property "
  "name=\"expand\">False</property>\n                                     "
  "               <property name=\"fill\">False</property>\n              "
  "                                      <property name=\"position\">3</pr"
  "operty>\n                                                  </packing>\n"
  "                                                </child>\n             "
  "                                   <child>\n                           "
  "                       <widget class=\"GtkButton\" id=\"button-layout-M"
  "\">\n                                                    <property name"
  "=\"visible\">True</property>\n                                         "
  "           <property name=\"can_focus\">True</property>\n              "
  "                                      <property name=\"receives_default"
  "\">True</property>\n                                                   "
  " <property name=\"tooltip\" translatable=\"yes\">Maximize</property>\n "
  "                                                   <property name=\"res"
  "ponse_id\">0</property>\n                                              "
  "      <child>\n                                                      <w"
  "idget class=\"GtkImage\" id=\"image5\">\n                              "
  "                          <property name=\"visible\">True</property>\n "
  "                                                       <property name=\""
  "stock\">gtk-zoom-100</property>\n                                      "
  "                </widget>\n                                            "
  "        </child>\n                                                  </w"
  "idget>\n                                                  <packing>\n  "
  "                                                  <property name=\"expa"
  "nd\">False</property>\n                                                "
  "    <property name=\"fill\">False</property>\n                         "
  "                           <property name=\"position\">4</property>\n  "
  "                                                </packing>\n           "
  "                                     </child>\n                        "
  "                        <child>\n                                      "
  "            <widget class=\"GtkButton\" id=\"button-layout-C\">\n      "
  "                                              <property name=\"visible\""
  ">True</property>\n                                                    <"
  "property name=\"can_focus\">True</property>\n                          "
  "                          <property name=\"receives_default\">True</pro"
  "perty>\n                                                    <property n"
  "ame=\"tooltip\" translatable=\"yes\">Close</property>\n                "
  "                                    <property name=\"response_id\">0</p"
  "roperty>\n                                                    <child>\n"
  "                                                      <widget class=\"G"
  "tkImage\" id=\"image6\">\n                                             "
  "           <property name=\"visible\">True</property>\n                "
  "                                        <property name=\"stock\">gtk-cl"
  "ose</property>\n                                                      <"
  "/widget>\n                                                    </child>\n"
  "                                                  </widget>\n          "
  "                                        <packing>\n                    "
  "                                <property name=\"expand\">False</proper"
  "ty>\n                                                    <property name"
  "=\"fill\">False</property>\n                                           "
  "         <property name=\"position\">5</property>\n                    "
  "                              </packing>\n                             "
  "                   </child>\n                                          "
  "    </widget>\n                                            </child>\n  "
  "                                        </widget>\n                    "
  "                    </child>\n                                        <"
  "child>\n                                          <widget class=\"GtkLa"
  "bel\" id=\"label28\">\n                                            <pro"
  "perty name=\"visible\">True</property>\n                               "
  "             <property name=\"label\" translatable=\"yes\">Hidden</prop"
  "erty>\n                                            <property name=\"use"
  "_markup\">True</property>\n                                          </"
  "widget>\n                                          <packing>\n         "
  "                                   <property name=\"type\">label_item</"
  "property>\n                                          </packing>\n      "
  "                                  </child>\n                           "
  "           </widget>\n                                      <packing>\n"
  "                                        <property name=\"position\">2</"
  "property>\n                                      </packing>\n          "
  "                          </child>\n                                  <"
  "/widget>\n                                </child>\n                   "
  "           </widget>\n                            </child>\n           "
  "                 <child>\n                              <widget class=\""
  "GtkLabel\" id=\"label25\">\n                                <property n"
  "ame=\"visible\">True</property>\n                                <prope"
  "rty name=\"label\" translatable=\"yes\">&lt;b&gt;Button layout&lt;/b&gt"
  ";</property>\n                                <property name=\"use_mark"
  "up\">True</property>\n                              </widget>\n        "
  "                      <packing>\n                                <prope"
  "rty name=\"type\">label_item</property>\n                              "
  "</packing>\n                            </child>\n                     "
  "     </widget>\n                          <packing>\n                  "
  "          <property name=\"expand\">False</property>\n                 "
  "           <property name=\"fill\">False</property>\n                  "
  "          <property name=\"position\">2</property>\n                   "
  "       </packing>\n                        </child>\n                  "
  "    </widget>\n                      <packing>\n                       "
  " <property name=\"position\">1</property>\n                      </pack"
  "ing>\n                    </child>\n                  </widget>\n      "
  "          </child>\n              </widget>\n            </child>\n    "
  "        <child>\n              <widget class=\"GtkLabel\" id=\"label1\""
  ">\n                <property name=\"visible\">True</property>\n        "
  "        <property name=\"label\" translatable=\"yes\">Style</property>\n"
  "              </widget>\n              <packing>\n                <prop"
  "erty name=\"type\">tab</property>\n                <property name=\"tab"
  "_fill\">False</property>\n              </packing>\n            </child"
  ">\n            <child>\n              <widget class=\"GtkAlignment\" id"
  "=\"alignment11\">\n                <property name=\"visible\">True</pro"
  "perty>\n                <property name=\"top_padding\">4</property>\n  "
  "              <property name=\"bottom_padding\">4</property>\n         "
  "       <property name=\"left_padding\">4</property>\n                <p"
  "roperty name=\"right_padding\">4</property>\n                <child>\n "
  "                 <widget class=\"GtkHBox\" id=\"hbox5\">\n             "
  "       <property name=\"visible\">True</property>\n                    "
  "<child>\n                      <widget class=\"GtkVBox\" id=\"vbox10\">"
  "\n                        <property name=\"visible\">True</property>\n "
  "                       <property name=\"spacing\">4</property>\n       "
  "                 <child>\n                          <widget class=\"Gtk"
  "ScrolledWindow\" id=\"scrolledwindow1\">\n                            <"
  "property name=\"visible\">True</property>\n                            "
  "<property name=\"can_focus\">True</property>\n                         "
  "   <property name=\"hscrollbar_policy\">GTK_POLICY_AUTOMATIC</property>"
  "\n                            <property name=\"vscrollbar_policy\">GTK_"
  "POLICY_AUTOMATIC</property>\n                            <property name"
  "=\"shadow_type\">GTK_SHADOW_IN</property>\n                            "
  "<child>\n                              <widget class=\"GtkTreeView\" id"
  "=\"keytheme_name_treeview\">\n                                <property"
  " name=\"visible\">True</property>\n                                <pro"
  "perty name=\"can_focus\">True</property>\n                             "
  "   <property name=\"headers_visible\">False</property>\n               "
  "               </widget>\n                            </child>\n       "
  "                   </widget>\n                        </child>\n       "
  "                 <child>\n                          <widget class=\"Gtk"
  "Button\" id=\"add_keytheme_button\">\n                            <prop"
  "erty name=\"visible\">True</property>\n                            <pro"
  "perty name=\"can_focus\">True</property>\n                            <"
  "property name=\"receives_default\">True</property>\n                   "
  "         <property name=\"label\" translatable=\"yes\">gtk-add</propert"
  "y>\n                            <property name=\"use_stock\">True</prop"
  "erty>\n                            <property name=\"response_id\">0</pr"
  "operty>\n                          </widget>\n                         "
  " <packing>\n                            <property name=\"expand\">False"
  "</property>\n                            <property name=\"fill\">False<"
  "/property>\n                            <property name=\"position\">1</"
  "property>\n                          </packing>\n                      "
  "  </child>\n                        <child>\n                          "
  "<widget class=\"GtkButton\" id=\"del_keytheme_button\">\n              "
  "              <property name=\"visible\">True</property>\n             "
  "               <property name=\"sensitive\">False</property>\n         "
  "                   <property name=\"can_focus\">True</property>\n      "
  "                      <property name=\"receives_default\">True</propert"
  "y>\n                            <property name=\"label\" translatable=\""
  "yes\">gtk-remove</property>\n                            <property name"
  "=\"use_stock\">True</property>\n                            <property n"
  "ame=\"response_id\">0</property>\n                          </widget>\n"
  "                          <packing>\n                            <prope"
  "rty name=\"expand\">False</property>\n                            <prop"
  "erty name=\"fill\">False</property>\n                            <prope"
  "rty name=\"position\">2</property>\n                          </packing"
  ">\n                        </child>\n                      </widget>\n "
  "                     <packing>\n                        <property name="
  "\"expand\">False</property>\n                        <property name=\"f"
  "ill\">False</property>\n                        <property name=\"paddin"
  "g\">4</property>\n                      </packing>\n                   "
  " </child>\n                    <child>\n                      <widget c"
  "lass=\"GtkFrame\" id=\"frame9\">\n                        <property nam"
  "e=\"visible\">True</property>\n                        <property name=\""
  "label_xalign\">0</property>\n                        <property name=\"s"
  "hadow_type\">GTK_SHADOW_NONE</property>\n                        <child"
  ">\n                          <widget class=\"GtkAlignment\" id=\"alignm"
  "ent12\">\n                            <property name=\"visible\">True</"
  "property>\n                            <property name=\"left_padding\">"
  "12</property>\n                            <child>\n                   "
  "           <widget class=\"GtkScrolledWindow\" id=\"scrolledwindow2\">\n"
  "                                <property name=\"visible\">True</proper"
  "ty>\n                                <property name=\"can_focus\">True<"
  "/property>\n                                <property name=\"hscrollbar"
  "_policy\">GTK_POLICY_AUTOMATIC</property>\n                            "
  "    <property name=\"shadow_type\">GTK_SHADOW_IN</property>\n          "
  "                      <child>\n                                  <widge"
  "t class=\"GtkTreeView\" id=\"keytheme_contents_treeview\">\n           "
  "                         <property name=\"visible\">True</property>\n  "
  "                                  <property name=\"sensitive\">False</p"
  "roperty>\n                                    <property name=\"can_focu"
  "s\">True</property>\n                                    <property name"
  "=\"headers_clickable\">True</property>\n                               "
  "   </widget>\n                                </child>\n               "
  "               </widget>\n                            </child>\n       "
  "                   </widget>\n                        </child>\n       "
  "                 <child>\n                          <widget class=\"Gtk"
  "Label\" id=\"label22\">\n                            <property name=\"v"
  "isible\">True</property>\n                            <property name=\""
  "label\" translatable=\"yes\">&lt;b&gt;Window shortcuts&lt;/b&gt;</prope"
  "rty>\n                            <property name=\"use_markup\">True</p"
  "roperty>\n                          </widget>\n                        "
  "  <packing>\n                            <property name=\"type\">label_"
  "item</property>\n                          </packing>\n                "
  "        </child>\n                      </widget>\n                    "
  "  <packing>\n                        <property name=\"position\">1</pro"
  "perty>\n                      </packing>\n                    </child>\n"
  "                  </widget>\n                </child>\n              </"
  "widget>\n              <packing>\n                <property name=\"posi"
  "tion\">1</property>\n              </packing>\n            </child>\n  "
  "          <child>\n              <widget class=\"GtkLabel\" id=\"label2"
  "\">\n                <property name=\"visible\">True</property>\n      "
  "          <property name=\"label\" translatable=\"yes\">Keyboard</prope"
  "rty>\n              </widget>\n              <packing>\n               "
  " <property name=\"type\">tab</property>\n                <property name"
  "=\"position\">1</property>\n                <property name=\"tab_fill\""
  ">False</property>\n              </packing>\n            </child>\n    "
  "        <child>\n              <widget class=\"GtkAlignment\" id=\"alig"
  "nment6\">\n                <property name=\"visible\">True</property>\n"
  "                <property name=\"top_padding\">4</property>\n          "
  "      <property name=\"bottom_padding\">4</property>\n                <"
  "property name=\"left_padding\">4</property>\n                <property "
  "name=\"right_padding\">4</property>\n                <child>\n         "
  "         <widget class=\"GtkVBox\" id=\"vbox7\">\n                    <"
  "property name=\"visible\">True</property>\n                    <propert"
  "y name=\"spacing\">4</property>\n                    <child>\n         "
  "             <widget class=\"GtkFrame\" id=\"frame5\">\n               "
  "         <property name=\"visible\">True</property>\n                  "
  "      <property name=\"label_xalign\">0</property>\n                   "
  "     <property name=\"shadow_type\">GTK_SHADOW_NONE</property>\n       "
  "                 <child>\n                          <widget class=\"Gtk"
  "Alignment\" id=\"alignment7\">\n                            <property n"
  "ame=\"visible\">True</property>\n                            <property "
  "name=\"left_padding\">12</property>\n                            <prope"
  "rty name=\"right_padding\">12</property>\n                            <"
  "child>\n                              <widget class=\"GtkHBox\" id=\"hb"
  "ox3\">\n                                <property name=\"visible\">True"
  "</property>\n                                <property name=\"homogeneo"
  "us\">True</property>\n                                <child>\n        "
  "                          <widget class=\"GtkRadioButton\" id=\"click_t"
  "o_focus_mode\">\n                                    <property name=\"v"
  "isible\">True</property>\n                                    <property"
  " name=\"can_focus\">True</property>\n                                  "
  "  <property name=\"label\" translatable=\"yes\">Click to focus</propert"
  "y>\n                                    <property name=\"response_id\">"
  "0</property>\n                                    <property name=\"acti"
  "ve\">True</property>\n                                    <property nam"
  "e=\"draw_indicator\">True</property>\n                                 "
  " </widget>\n                                </child>\n                 "
  "               <child>\n                                  <widget class"
  "=\"GtkRadioButton\" id=\"radiobutton2\">\n                             "
  "       <property name=\"visible\">True</property>\n                    "
  "                <property name=\"can_focus\">True</property>\n         "
  "                           <property name=\"label\" translatable=\"yes\""
  ">Focus follows mouse</property>\n                                    <p"
  "roperty name=\"response_id\">0</property>\n                            "
  "        <property name=\"active\">True</property>\n                    "
  "                <property name=\"draw_indicator\">True</property>\n    "
  "                                <property name=\"group\">click_to_focus"
  "_mode</property>\n                                  </widget>\n        "
  "                          <packing>\n                                  "
  "  <property name=\"position\">1</property>\n                           "
  "       </packing>\n                                </child>\n          "
  "                    </widget>\n                            </child>\n  "
  "                        </widget>\n                        </child>\n  "
  "                      <child>\n                          <widget class="
  "\"GtkLabel\" id=\"label15\">\n                            <property nam"
  "e=\"visible\">True</property>\n                            <property na"
  "me=\"label\" translatable=\"yes\">&lt;b&gt;Focus model&lt;/b&gt;</prope"
  "rty>\n                            <property name=\"use_markup\">True</p"
  "roperty>\n                          </widget>\n                        "
  "  <packing>\n                            <property name=\"type\">label_"
  "item</property>\n                          </packing>\n                "
  "        </child>\n                      </widget>\n                    "
  "  <packing>\n                        <property name=\"expand\">False</p"
  "roperty>\n                        <property name=\"fill\">False</proper"
  "ty>\n                      </packing>\n                    </child>\n  "
  "                  <child>\n                      <widget class=\"GtkFra"
  "me\" id=\"frame13\">\n                        <property name=\"visible\""
  ">True</property>\n                        <property name=\"label_xalign"
  "\">0</property>\n                        <property name=\"shadow_type\""
  ">GTK_SHADOW_NONE</property>\n                        <child>\n         "
  "                 <widget class=\"GtkAlignment\" id=\"alignment19\">\n  "
  "                          <property name=\"visible\">True</property>\n "
  "                           <property name=\"left_padding\">12</property"
  ">\n                            <child>\n                              <"
  "widget class=\"GtkHBox\" id=\"hbox6\">\n                               "
  " <property name=\"visible\">True</property>\n                          "
  "      <property name=\"spacing\">4</property>\n                        "
  "        <child>\n                                  <widget class=\"GtkL"
  "abel\" id=\"label30\">\n                                    <property n"
  "ame=\"visible\">True</property>\n                                    <p"
  "roperty name=\"label\" translatable=\"yes\">&lt;i&gt;Short&lt;/i&gt;</p"
  "roperty>\n                                    <property name=\"use_mark"
  "up\">True</property>\n                                  </widget>\n    "
  "                              <packing>\n                              "
  "      <property name=\"expand\">False</property>\n                     "
  "               <property name=\"fill\">False</property>\n              "
  "                    </packing>\n                                </child"
  ">\n                                <child>\n                           "
  "       <widget class=\"GtkHScale\" id=\"focus_delay_scale\">\n         "
  "                           <property name=\"visible\">True</property>\n"
  "                                    <property name=\"can_focus\">True</"
  "property>\n                                    <property name=\"update_"
  "policy\">GTK_UPDATE_DISCONTINUOUS</property>\n                         "
  "           <property name=\"adjustment\">100 100 2000 1 10 10</property"
  ">\n                                    <property name=\"draw_value\">Fa"
  "lse</property>\n                                  </widget>\n          "
  "                        <packing>\n                                    "
  "<property name=\"position\">1</property>\n                             "
  "     </packing>\n                                </child>\n            "
  "                    <child>\n                                  <widget "
  "class=\"GtkLabel\" id=\"label31\">\n                                   "
  " <property name=\"visible\">True</property>\n                          "
  "          <property name=\"label\" translatable=\"yes\">&lt;i&gt;Long&l"
  "t;/i&gt;</property>\n                                    <property name"
  "=\"use_markup\">True</property>\n                                  </wi"
  "dget>\n                                  <packing>\n                   "
  "                 <property name=\"expand\">False</property>\n          "
  "                          <property name=\"fill\">False</property>\n   "
  "                                 <property name=\"position\">2</propert"
  "y>\n                                  </packing>\n                     "
  "           </child>\n                              </widget>\n         "
  "                   </child>\n                          </widget>\n     "
  "                   </child>\n                        <child>\n         "
  "                 <widget class=\"GtkLabel\" id=\"label29\">\n          "
  "                  <property name=\"visible\">True</property>\n         "
  "                   <property name=\"label\" translatable=\"yes\">&lt;b&"
  "gt;Delay before window receives focus&lt;/b&gt;</property>\n           "
  "                 <property name=\"use_markup\">True</property>\n       "
  "                   </widget>\n                          <packing>\n    "
  "                        <property name=\"type\">label_item</property>\n"
  "                          </packing>\n                        </child>\n"
  "                      </widget>\n                      <packing>\n     "
  "                   <property name=\"expand\">False</property>\n        "
  "                <property name=\"position\">1</property>\n             "
  "         </packing>\n                    </child>\n                    "
  "<child>\n                      <widget class=\"GtkFrame\" id=\"frame6\""
  ">\n                        <property name=\"visible\">True</property>\n"
  "                        <property name=\"label_xalign\">0</property>\n "
  "                       <property name=\"shadow_type\">GTK_SHADOW_NONE</"
  "property>\n                        <child>\n                          <"
  "widget class=\"GtkAlignment\" id=\"alignment8\">\n                     "
  "       <property name=\"visible\">True</property>\n                    "
  "        <property name=\"left_padding\">12</property>\n                "
  "            <property name=\"right_padding\">12</property>\n           "
  "                 <child>\n                              <widget class=\""
  "GtkCheckButton\" id=\"focus_new_check\">\n                             "
  "   <property name=\"visible\">True</property>\n                        "
  "        <property name=\"can_focus\">True</property>\n                 "
  "               <property name=\"label\" translatable=\"yes\">Automatica"
  "lly give focus to newly created windows</property>\n                   "
  "             <property name=\"response_id\">0</property>\n             "
  "                   <property name=\"draw_indicator\">True</property>\n "
  "                             </widget>\n                            </c"
  "hild>\n                          </widget>\n                        </c"
  "hild>\n                        <child>\n                          <widg"
  "et class=\"GtkLabel\" id=\"label16\">\n                            <pro"
  "perty name=\"visible\">True</property>\n                            <pr"
  "operty name=\"label\" translatable=\"yes\">&lt;b&gt;New window focus&lt"
  ";/b&gt;</property>\n                            <property name=\"use_ma"
  "rkup\">True</property>\n                          </widget>\n          "
  "                <packing>\n                            <property name=\""
  "type\">label_item</property>\n                          </packing>\n   "
  "                     </child>\n                      </widget>\n       "
  "               <packing>\n                        <property name=\"expa"
  "nd\">False</property>\n                        <property name=\"fill\">"
  "False</property>\n                        <property name=\"position\">2"
  "</property>\n                      </packing>\n                    </ch"
  "ild>\n                    <child>\n                      <widget class="
  "\"GtkFrame\" id=\"frame7\">\n                        <property name=\"v"
  "isible\">True</property>\n                        <property name=\"labe"
  "l_xalign\">0</property>\n                        <property name=\"shado"
  "w_type\">GTK_SHADOW_NONE</property>\n                        <child>\n "
  "                         <widget class=\"GtkAlignment\" id=\"alignment9"
  "\">\n                            <property name=\"visible\">True</prope"
  "rty>\n                            <property name=\"left_padding\">12</p"
  "roperty>\n                            <property name=\"right_padding\">"
  "12</property>\n                            <child>\n                   "
  "           <widget class=\"GtkVBox\" id=\"vbox8\">\n                   "
  "             <property name=\"visible\">True</property>\n              "
  "                  <property name=\"spacing\">4</property>\n            "
  "                    <child>\n                                  <widget "
  "class=\"GtkCheckButton\" id=\"raise_on_focus_check\">\n                "
  "                    <property name=\"visible\">True</property>\n       "
  "                             <property name=\"can_focus\">True</propert"
  "y>\n                                    <property name=\"label\" transl"
  "atable=\"yes\">Automatically raise windows when they receive focus</pro"
  "perty>\n                                    <property name=\"response_i"
  "d\">0</property>\n                                    <property name=\""
  "draw_indicator\">True</property>\n                                  </w"
  "idget>\n                                </child>\n                     "
  "           <child>\n                                  <widget class=\"G"
  "tkVBox\" id=\"vbox9\">\n                                    <property n"
  "ame=\"visible\">True</property>\n                                    <c"
  "hild>\n                                      <widget class=\"GtkLabel\""
  " id=\"label19\">\n                                        <property nam"
  "e=\"visible\">True</property>\n                                        "
  "<property name=\"xalign\">0</property>\n                               "
  "         <property name=\"label\" translatable=\"yes\">Delay before rai"
  "sing focused window:</property>\n                                      "
  "</widget>\n                                      <packing>\n           "
  "                             <property name=\"expand\">False</property>"
  "\n                                        <property name=\"fill\">False"
  "</property>\n                                      </packing>\n        "
  "                            </child>\n                                 "
  "   <child>\n                                      <widget class=\"GtkHB"
  "ox\" id=\"hbox4\">\n                                        <property n"
  "ame=\"visible\">True</property>\n                                      "
  "  <property name=\"spacing\">4</property>\n                            "
  "            <child>\n                                          <widget "
  "class=\"GtkLabel\" id=\"label20\">\n                                   "
  "         <property name=\"visible\">True</property>\n                  "
  "                          <property name=\"label\" translatable=\"yes\""
  ">&lt;i&gt;Short&lt;/i&gt;</property>\n                                 "
  "           <property name=\"use_markup\">True</property>\n             "
  "                             </widget>\n                               "
  "           <packing>\n                                            <prop"
  "erty name=\"expand\">False</property>\n                                "
  "            <property name=\"fill\">False</property>\n                 "
  "                         </packing>\n                                  "
  "      </child>\n                                        <child>\n      "
  "                                    <widget class=\"GtkHScale\" id=\"fo"
  "cus_raise_delay_scale\">\n                                            <"
  "property name=\"visible\">True</property>\n                            "
  "                <property name=\"can_focus\">True</property>\n         "
  "                                   <property name=\"update_policy\">GTK"
  "_UPDATE_DISCONTINUOUS</property>\n                                     "
  "       <property name=\"adjustment\">100 100 2000 1 10 10</property>\n "
  "                                           <property name=\"draw_value\""
  ">False</property>\n                                          </widget>\n"
  "                                          <packing>\n                  "
  "                          <property name=\"position\">1</property>\n   "
  "                                       </packing>\n                    "
  "                    </child>\n                                        <"
  "child>\n                                          <widget class=\"GtkLa"
  "bel\" id=\"label21\">\n                                            <pro"
  "perty name=\"visible\">True</property>\n                               "
  "             <property name=\"label\" translatable=\"yes\">&lt;i&gt;Lon"
  "g&lt;/i&gt;</property>\n                                            <pr"
  "operty name=\"use_markup\">True</property>\n                           "
  "               </widget>\n                                          <pa"
  "cking>\n                                            <property name=\"ex"
  "pand\">False</property>\n                                            <p"
  "roperty name=\"fill\">False</property>\n                               "
  "             <property name=\"position\">2</property>\n                "
  "                          </packing>\n                                 "
  "       </child>\n                                      </widget>\n     "
  "                                 <packing>\n                           "
  "             <property name=\"position\">1</property>\n                "
  "                      </packing>\n                                    <"
  "/child>\n                                  </widget>\n                 "
  "                 <packing>\n                                    <proper"
  "ty name=\"position\">1</property>\n                                  </"
  "packing>\n                                </child>\n                   "
  "           </widget>\n                            </child>\n           "
  "               </widget>\n                        </child>\n           "
  "             <child>\n                          <widget class=\"GtkLabe"
  "l\" id=\"label17\">\n                            <property name=\"visib"
  "le\">True</property>\n                            <property name=\"labe"
  "l\" translatable=\"yes\">&lt;b&gt;Raise on focus&lt;/b&gt;</property>\n"
  "                            <property name=\"use_markup\">True</propert"
  "y>\n                          </widget>\n                          <pac"
  "king>\n                            <property name=\"type\">label_item</"
  "property>\n                          </packing>\n                      "
  "  </child>\n                      </widget>\n                      <pac"
  "king>\n                        <property name=\"expand\">False</propert"
  "y>\n                        <property name=\"fill\">False</property>\n "
  "                       <property name=\"position\">3</property>\n      "
  "                </packing>\n                    </child>\n             "
  "       <child>\n                      <widget class=\"GtkFrame\" id=\"f"
  "rame8\">\n                        <property name=\"visible\">True</prop"
  "erty>\n                        <property name=\"label_xalign\">0</prope"
  "rty>\n                        <property name=\"shadow_type\">GTK_SHADOW"
  "_NONE</property>\n                        <child>\n                    "
  "      <widget class=\"GtkAlignment\" id=\"alignment10\">\n             "
  "               <property name=\"visible\">True</property>\n            "
  "                <property name=\"left_padding\">12</property>\n        "
  "                    <property name=\"right_padding\">12</property>\n   "
  "                         <child>\n                              <widget"
  " class=\"GtkCheckButton\" id=\"raise_on_click_check\">\n               "
  "                 <property name=\"visible\">True</property>\n          "
  "                      <property name=\"can_focus\">True</property>\n   "
  "                             <property name=\"label\" translatable=\"ye"
  "s\">Raise window when clicking inside application window</property>\n  "
  "                              <property name=\"response_id\">0</propert"
  "y>\n                                <property name=\"draw_indicator\">T"
  "rue</property>\n                              </widget>\n              "
  "              </child>\n                          </widget>\n          "
  "              </child>\n                        <child>\n              "
  "            <widget class=\"GtkLabel\" id=\"label18\">\n               "
  "             <property name=\"visible\">True</property>\n              "
  "              <property name=\"label\" translatable=\"yes\">&lt;b&gt;Ra"
  "ise on click&lt;/b&gt;</property>\n                            <propert"
  "y name=\"use_markup\">True</property>\n                          </widg"
  "et>\n                          <packing>\n                            <"
  "property name=\"type\">label_item</property>\n                         "
  " </packing>\n                        </child>\n                      </"
  "widget>\n                      <packing>\n                        <prop"
  "erty name=\"expand\">False</property>\n                        <propert"
  "y name=\"fill\">False</property>\n                        <property nam"
  "e=\"position\">4</property>\n                      </packing>\n        "
  "            </child>\n                  </widget>\n                </ch"
  "ild>\n              </widget>\n              <packing>\n               "
  " <property name=\"position\">2</property>\n              </packing>\n  "
  "          </child>\n            <child>\n              <widget class=\""
  "GtkLabel\" id=\"label3\">\n                <property name=\"visible\">T"
  "rue</property>\n                <property name=\"label\" translatable=\""
  "yes\">Focus</property>\n              </widget>\n              <packing"
  ">\n                <property name=\"type\">tab</property>\n            "
  "    <property name=\"position\">2</property>\n                <property"
  " name=\"tab_fill\">False</property>\n              </packing>\n        "
  "    </child>\n            <child>\n              <widget class=\"GtkAli"
  "gnment\" id=\"alignment1\">\n                <property name=\"visible\""
  ">True</property>\n                <property name=\"top_padding\">4</pro"
  "perty>\n                <property name=\"bottom_padding\">4</property>\n"
  "                <property name=\"left_padding\">4</property>\n         "
  "       <property name=\"right_padding\">4</property>\n                <"
  "child>\n                  <widget class=\"GtkVBox\" id=\"vbox1\">\n    "
  "                <property name=\"visible\">True</property>\n           "
  "         <child>\n                      <widget class=\"GtkFrame\" id=\""
  "frame1\">\n                        <property name=\"visible\">True</pro"
  "perty>\n                        <property name=\"label_xalign\">0</prop"
  "erty>\n                        <property name=\"shadow_type\">GTK_SHADO"
  "W_NONE</property>\n                        <child>\n                   "
  "       <widget class=\"GtkAlignment\" id=\"alignment2\">\n             "
  "               <property name=\"visible\">True</property>\n            "
  "                <property name=\"left_padding\">12</property>\n        "
  "                    <property name=\"right_padding\">12</property>\n   "
  "                         <child>\n                              <widget"
  " class=\"GtkVBox\" id=\"vbox2\">\n                                <prop"
  "erty name=\"visible\">True</property>\n                                "
  "<property name=\"spacing\">4</property>\n                              "
  "  <child>\n                                  <widget class=\"GtkCheckBu"
  "tton\" id=\"snap_to_border_check\">\n                                  "
  "  <property name=\"visible\">True</property>\n                         "
  "           <property name=\"can_focus\">True</property>\n              "
  "                      <property name=\"label\" translatable=\"yes\">Sna"
  "p windows to screen border</property>\n                                "
  "    <property name=\"response_id\">0</property>\n                      "
  "              <property name=\"draw_indicator\">True</property>\n      "
  "                            </widget>\n                                "
  "  <packing>\n                                    <property name=\"expan"
  "d\">False</property>\n                                    <property nam"
  "e=\"fill\">False</property>\n                                  </packin"
  "g>\n                                </child>\n                         "
  "       <child>\n                                  <widget class=\"GtkCh"
  "eckButton\" id=\"snap_to_window_check\">\n                             "
  "       <property name=\"visible\">True</property>\n                    "
  "                <property name=\"can_focus\">True</property>\n         "
  "                           <property name=\"label\" translatable=\"yes\""
  ">Snap windows to other windows</property>\n                            "
  "        <property name=\"response_id\">0</property>\n                  "
  "                  <property name=\"draw_indicator\">True</property>\n  "
  "                                </widget>\n                            "
  "      <packing>\n                                    <property name=\"e"
  "xpand\">False</property>\n                                    <property"
  " name=\"fill\">False</property>\n                                    <p"
  "roperty name=\"position\">1</property>\n                               "
  "   </packing>\n                                </child>\n              "
  "                  <child>\n                                  <widget cl"
  "ass=\"GtkVBox\" id=\"vbox5\">\n                                    <pro"
  "perty name=\"visible\">True</property>\n                               "
  "     <child>\n                                      <widget class=\"Gtk"
  "Label\" id=\"label9\">\n                                        <proper"
  "ty name=\"visible\">True</property>\n                                  "
  "      <property name=\"xalign\">0</property>\n                         "
  "               <property name=\"label\" translatable=\"yes\">Distance:<"
  "/property>\n                                      </widget>\n          "
  "                          </child>\n                                   "
  " <child>\n                                      <widget class=\"GtkHBox"
  "\" id=\"hbox1\">\n                                        <property nam"
  "e=\"visible\">True</property>\n                                        "
  "<property name=\"spacing\">4</property>\n                              "
  "          <child>\n                                          <widget cl"
  "ass=\"GtkLabel\" id=\"label11\">\n                                     "
  "       <property name=\"visible\">True</property>\n                    "
  "                        <property name=\"label\" translatable=\"yes\">&"
  "lt;i&gt;Small&lt;/i&gt;</property>\n                                   "
  "         <property name=\"use_markup\">True</property>\n               "
  "                           </widget>\n                                 "
  "         <packing>\n                                            <proper"
  "ty name=\"expand\">False</property>\n                                  "
  "          <property name=\"fill\">False</property>\n                   "
  "                       </packing>\n                                    "
  "    </child>\n                                        <child>\n        "
  "                                  <widget class=\"GtkHScale\" id=\"snap"
  "_width_scale\">\n                                            <property "
  "name=\"visible\">True</property>\n                                     "
  "       <property name=\"can_focus\">True</property>\n                  "
  "                          <property name=\"update_policy\">GTK_UPDATE_D"
  "ISCONTINUOUS</property>\n                                            <p"
  "roperty name=\"adjustment\">20.332225913621262 0 100 1 10 10</property>"
  "\n                                            <property name=\"restrict"
  "_to_fill_level\">False</property>\n                                    "
  "        <property name=\"draw_value\">False</property>\n               "
  "                           </widget>\n                                 "
  "         <packing>\n                                            <proper"
  "ty name=\"position\">1</property>\n                                    "
  "      </packing>\n                                        </child>\n   "
  "                                     <child>\n                         "
  "                 <widget class=\"GtkLabel\" id=\"label12\">\n          "
  "                                  <property name=\"visible\">True</prop"
  "erty>\n                                            <property name=\"lab"
  "el\" translatable=\"yes\">&lt;i&gt;Wide&lt;/i&gt;</property>\n         "
  "                                   <property name=\"use_markup\">True</"
  "property>\n                                          </widget>\n       "
  "                                   <packing>\n                         "
  "                   <property name=\"expand\">False</property>\n        "
  "                                    <property name=\"fill\">False</prop"
  "erty>\n                                            <property name=\"pos"
  "ition\">2</property>\n                                          </packi"
  "ng>\n                                        </child>\n                "
  "                      </widget>\n                                      "
  "<packing>\n                                        <property name=\"pos"
  "ition\">1</property>\n                                      </packing>\n"
  "                                    </child>\n                         "
  "         </widget>\n                                  <packing>\n      "
  "                              <property name=\"position\">2</property>\n"
  "                                  </packing>\n                         "
  "       </child>\n                              </widget>\n             "
  "               </child>\n                          </widget>\n         "
  "               </child>\n                        <child>\n             "
  "             <widget class=\"GtkLabel\" id=\"label5\">\n               "
  "             <property name=\"visible\">True</property>\n              "
  "              <property name=\"label\" translatable=\"yes\">&lt;b&gt;Wi"
  "ndows snapping&lt;/b&gt;</property>\n                            <prope"
  "rty name=\"use_markup\">True</property>\n                          </wi"
  "dget>\n                          <packing>\n                           "
  " <property name=\"type\">label_item</property>\n                       "
  "   </packing>\n                        </child>\n                      "
  "</widget>\n                    </child>\n                    <child>\n "
  "                     <widget class=\"GtkFrame\" id=\"frame2\">\n       "
  "                 <property name=\"visible\">True</property>\n          "
  "              <property name=\"label_xalign\">0</property>\n           "
  "             <property name=\"shadow_type\">GTK_SHADOW_NONE</property>\n"
  "                        <child>\n                          <widget clas"
  "s=\"GtkAlignment\" id=\"alignment3\">\n                            <pro"
  "perty name=\"visible\">True</property>\n                            <pr"
  "operty name=\"left_padding\">12</property>\n                           "
  " <property name=\"right_padding\">12</property>\n                      "
  "      <child>\n                              <widget class=\"GtkVBox\" "
  "id=\"vbox4\">\n                                <property name=\"visible"
  "\">True</property>\n                                <property name=\"sp"
  "acing\">4</property>\n                                <child>\n        "
  "                          <widget class=\"GtkCheckButton\" id=\"wrap_wo"
  "rkspaces_check\">\n                                    <property name=\""
  "visible\">True</property>\n                                    <propert"
  "y name=\"can_focus\">True</property>\n                                 "
  "   <property name=\"label\" translatable=\"yes\">Wrap workspaces when t"
  "he pointer reaches the screen edge</property>\n                        "
  "            <property name=\"response_id\">0</property>\n              "
  "                      <property name=\"draw_indicator\">True</property>"
  "\n                                  </widget>\n                        "
  "        </child>\n                                <child>\n            "
  "                      <widget class=\"GtkCheckButton\" id=\"wrap_window"
  "s_check\">\n                                    <property name=\"visibl"
  "e\">True</property>\n                                    <property name"
  "=\"can_focus\">True</property>\n                                    <pr"
  "operty name=\"label\" translatable=\"yes\">Wrap workspaces when draggin"
  "g a window off the screen</property>\n                                 "
  "   <property name=\"response_id\">0</property>\n                       "
  "             <property name=\"draw_indicator\">True</property>\n       "
  "                           </widget>\n                                 "
  " <packing>\n                                    <property name=\"positi"
  "on\">1</property>\n                                  </packing>\n      "
  "                          </child>\n                                <ch"
  "ild>\n                                  <widget class=\"GtkVBox\" id=\""
  "vbox6\">\n                                    <property name=\"visible\""
  ">True</property>\n                                    <child>\n        "
  "                              <widget class=\"GtkLabel\" id=\"label10\""
  ">\n                                        <property name=\"visible\">T"
  "rue</property>\n                                        <property name="
  "\"xalign\">0</property>\n                                        <prope"
  "rty name=\"label\" translatable=\"yes\">Edge resistance:</property>\n  "
  "                                      <property name=\"selectable\">Tru"
  "e</property>\n                                      </widget>\n        "
  "                              <packing>\n                              "
  "          <property name=\"expand\">False</property>\n                 "
  "                       <property name=\"fill\">False</property>\n      "
  "                                </packing>\n                           "
  "         </child>\n                                    <child>\n       "
  "                               <widget class=\"GtkHBox\" id=\"hbox2\">\n"
  "                                        <property name=\"visible\">True"
  "</property>\n                                        <property name=\"s"
  "pacing\">4</property>\n                                        <child>\n"
  "                                          <widget class=\"GtkLabel\" id"
  "=\"label13\">\n                                            <property na"
  "me=\"visible\">True</property>\n                                       "
  "     <property name=\"label\" translatable=\"yes\">&lt;i&gt;Small&lt;/i"
  "&gt;</property>\n                                            <property "
  "name=\"use_markup\">True</property>\n                                  "
  "        </widget>\n                                          <packing>\n"
  "                                            <property name=\"expand\">F"
  "alse</property>\n                                            <property "
  "name=\"fill\">False</property>\n                                       "
  "   </packing>\n                                        </child>\n      "
  "                                  <child>\n                            "
  "              <widget class=\"GtkHScale\" id=\"wrap_resistance_scale\">"
  "\n                                            <property name=\"visible\""
  ">True</property>\n                                            <property"
  " name=\"can_focus\">True</property>\n                                  "
  "          <property name=\"update_policy\">GTK_UPDATE_DISCONTINUOUS</pr"
  "operty>\n                                            <property name=\"a"
  "djustment\">20.332225913621262 0 100 1 10 10</property>\n              "
  "                              <property name=\"restrict_to_fill_level\""
  ">False</property>\n                                            <propert"
  "y name=\"draw_value\">False</property>\n                               "
  "           </widget>\n                                          <packin"
  "g>\n                                            <property name=\"positi"
  "on\">1</property>\n                                          </packing>"
  "\n                                        </child>\n                   "
  "                     <child>\n                                         "
  " <widget class=\"GtkLabel\" id=\"label14\">\n                          "
  "                  <property name=\"visible\">True</property>\n         "
  "                                   <property name=\"label\" translatabl"
  "e=\"yes\">&lt;i&gt;Wide&lt;/i&gt;</property>\n                         "
  "                   <property name=\"use_markup\">True</property>\n     "
  "                                     </widget>\n                       "
  "                   <packing>\n                                         "
  "   <property name=\"expand\">False</property>\n                        "
  "                    <property name=\"fill\">False</property>\n         "
  "                                   <property name=\"position\">2</prope"
  "rty>\n                                          </packing>\n           "
  "                             </child>\n                                "
  "      </widget>\n                                      <packing>\n     "
  "                                   <property name=\"position\">1</prope"
  "rty>\n                                      </packing>\n               "
  "                     </child>\n                                  </widg"
  "et>\n                                  <packing>\n                     "
  "               <property name=\"position\">2</property>\n              "
  "                    </packing>\n                                </child"
  ">\n                              </widget>\n                           "
  " </child>\n                          </widget>\n                       "
  " </child>\n                        <child>\n                          <"
  "widget class=\"GtkLabel\" id=\"label6\">\n                            <"
  "property name=\"visible\">True</property>\n                            "
  "<property name=\"label\" translatable=\"yes\">&lt;b&gt;Wrap workspaces&"
  "lt;/b&gt;</property>\n                            <property name=\"use_"
  "markup\">True</property>\n                          </widget>\n        "
  "                  <packing>\n                            <property name"
  "=\"type\">label_item</property>\n                          </packing>\n"
  "                        </child>\n                      </widget>\n    "
  "                  <packing>\n                        <property name=\"p"
  "osition\">1</property>\n                      </packing>\n             "
  "       </child>\n                    <child>\n                      <wi"
  "dget class=\"GtkFrame\" id=\"frame3\">\n                        <proper"
  "ty name=\"visible\">True</property>\n                        <property "
  "name=\"label_xalign\">0</property>\n                        <property n"
  "ame=\"shadow_type\">GTK_SHADOW_NONE</property>\n                       "
  " <child>\n                          <widget class=\"GtkAlignment\" id=\""
  "alignment4\">\n                            <property name=\"visible\">T"
  "rue</property>\n                            <property name=\"left_paddi"
  "ng\">12</property>\n                            <property name=\"right_"
  "padding\">12</property>\n                            <child>\n         "
  "                     <widget class=\"GtkVBox\" id=\"vbox3\">\n         "
  "                       <property name=\"visible\">True</property>\n    "
  "                            <property name=\"spacing\">4</property>\n  "
  "                              <child>\n                                "
  "  <widget class=\"GtkCheckButton\" id=\"box_resize_check\">\n          "
  "                          <property name=\"visible\">True</property>\n "
  "                                   <property name=\"can_focus\">True</p"
  "roperty>\n                                    <property name=\"label\" "
  "translatable=\"yes\">Hide content of windows when resizing</property>\n"
  "                                    <property name=\"response_id\">0</p"
  "roperty>\n                                    <property name=\"draw_ind"
  "icator\">True</property>\n                                  </widget>\n"
  "                                  <packing>\n                          "
  "          <property name=\"expand\">False</property>\n                 "
  "                   <property name=\"fill\">False</property>\n          "
  "                        </packing>\n                                </c"
  "hild>\n                                <child>\n                       "
  "           <widget class=\"GtkCheckButton\" id=\"box_move_check\">\n   "
  "                                 <property name=\"visible\">True</prope"
  "rty>\n                                    <property name=\"can_focus\">"
  "True</property>\n                                    <property name=\"l"
  "abel\" translatable=\"yes\">Hide content of windows when moving</proper"
  "ty>\n                                    <property name=\"response_id\""
  ">0</property>\n                                    <property name=\"dra"
  "w_indicator\">True</property>\n                                  </widg"
  "et>\n                                  <packing>\n                     "
  "               <property name=\"expand\">False</property>\n            "
  "                        <property name=\"fill\">False</property>\n     "
  "                               <property name=\"position\">1</property>"
  "\n                                  </packing>\n                       "
  "         </child>\n                              </widget>\n           "
  "                 </child>\n                          </widget>\n       "
  "                 </child>\n                        <child>\n           "
  "               <widget class=\"GtkLabel\" id=\"label7\">\n             "
  "               <property name=\"visible\">True</property>\n            "
  "                <property name=\"label\" translatable=\"yes\">&lt;b&gt;"
  "Box move and resize&lt;/b&gt;</property>\n                            <"
  "property name=\"use_markup\">True</property>\n                         "
  " </widget>\n                          <packing>\n                      "
  "      <property name=\"type\">label_item</property>\n                  "
  "        </packing>\n                        </child>\n                 "
  "     </widget>\n                      <packing>\n                      "
  "  <property name=\"position\">2</property>\n                      </pac"
  "king>\n                    </child>\n                    <child>\n     "
  "                 <widget class=\"GtkFrame\" id=\"frame4\">\n           "
  "             <property name=\"visible\">True</property>\n              "
  "          <property name=\"label_xalign\">0</property>\n               "
  "         <property name=\"shadow_type\">GTK_SHADOW_NONE</property>\n   "
  "                     <child>\n                          <widget class=\""
  "GtkAlignment\" id=\"alignment5\">\n                            <propert"
  "y name=\"visible\">True</property>\n                            <proper"
  "ty name=\"left_padding\">12</property>\n                            <pr"
  "operty name=\"right_padding\">12</property>\n                          "
  "  <child>\n                              <widget class=\"GtkComboBox\" "
  "id=\"double_click_action_combo\">\n                                <pro"
  "perty name=\"visible\">True</property>\n                               "
  " <property name=\"tooltip\" translatable=\"yes\">The action to perform "
  "when the title-bar is double-clicked</property>\n                      "
  "          <property name=\"items\" translatable=\"yes\">\t</property>\n"
  "                              </widget>\n                            </"
  "child>\n                          </widget>\n                        </"
  "child>\n                        <child>\n                          <wid"
  "get class=\"GtkLabel\" id=\"label8\">\n                            <pro"
  "perty name=\"visible\">True</property>\n                            <pr"
  "operty name=\"label\" translatable=\"yes\">&lt;b&gt;Double click action"
  "&lt;/b&gt;</property>\n                            <property name=\"use"
  "_markup\">True</property>\n                          </widget>\n       "
  "                   <packing>\n                            <property nam"
  "e=\"type\">label_item</property>\n                          </packing>\n"
  "                        </child>\n                      </widget>\n    "
  "                  <packing>\n                        <property name=\"p"
  "osition\">3</property>\n                      </packing>\n             "
  "       </child>\n                  </widget>\n                </child>\n"
  "              </widget>\n              <packing>\n                <prop"
  "erty name=\"position\">3</property>\n              </packing>\n        "
  "    </child>\n            <child>\n              <widget class=\"GtkLab"
  "el\" id=\"label4\">\n                <property name=\"visible\">True</p"
  "roperty>\n                <property name=\"label\" translatable=\"yes\""
  ">Advanced</property>\n              </widget>\n              <packing>\n"
  "                <property name=\"type\">tab</property>\n               "
  " <property name=\"position\">3</property>\n                <property na"
  "me=\"tab_fill\">False</property>\n              </packing>\n           "
  " </child>\n          </widget>\n          <packing>\n            <prope"
  "rty name=\"position\">2</property>\n          </packing>\n        </chi"
  "ld>\n        <child internal-child=\"action_area\">\n          <widget "
  "class=\"GtkHButtonBox\" id=\"dialog-action_area1\">\n            <prope"
  "rty name=\"visible\">True</property>\n            <property name=\"layo"
  "ut_style\">GTK_BUTTONBOX_EDGE</property>\n            <child>\n        "
  "      <widget class=\"GtkButton\" id=\"help_button\">\n                "
  "<property name=\"visible\">True</property>\n                <property n"
  "ame=\"can_focus\">True</property>\n                <property name=\"rec"
  "eives_default\">True</property>\n                <property name=\"label"
  "\" translatable=\"yes\">gtk-help</property>\n                <property "
  "name=\"use_stock\">True</property>\n                <property name=\"re"
  "sponse_id\">0</property>\n              </widget>\n            </child>"
  "\n            <child>\n              <widget class=\"GtkButton\" id=\"c"
  "lose_button\">\n                <property name=\"visible\">True</proper"
  "ty>\n                <property name=\"can_focus\">True</property>\n    "
  "            <property name=\"receives_default\">True</property>\n      "
  "          <property name=\"label\" translatable=\"yes\">gtk-close</prop"
  "erty>\n                <property name=\"use_stock\">True</property>\n  "
  "              <property name=\"response_id\">0</property>\n            "
  "  </widget>\n              <packing>\n                <property name=\""
  "position\">1</property>\n              </packing>\n            </child>"
  "\n          </widget>\n          <packing>\n            <property name="
  "\"expand\">False</property>\n            <property name=\"pack_type\">G"
  "TK_PACK_END</property>\n          </packing>\n        </child>\n      <"
  "/widget>\n    </child>\n  </widget>\n  <widget class=\"GtkDialog\" id=\""
  "add-keytheme-dialog\">\n    <property name=\"border_width\">5</property"
  ">\n    <property name=\"resizable\">False</property>\n    <property nam"
  "e=\"window_position\">GTK_WIN_POS_CENTER_ON_PARENT</property>\n    <pro"
  "perty name=\"type_hint\">GDK_WINDOW_TYPE_HINT_DIALOG</property>\n    <p"
  "roperty name=\"skip_taskbar_hint\">True</property>\n    <property name="
  "\"skip_pager_hint\">True</property>\n    <property name=\"transient_for"
  "\">main-dialog</property>\n    <property name=\"has_separator\">False</"
  "property>\n    <child internal-child=\"vbox\">\n      <widget class=\"G"
  "tkVBox\" id=\"dialog-vbox2\">\n        <property name=\"visible\">True<"
  "/property>\n        <property name=\"spacing\">2</property>\n        <c"
  "hild>\n          <widget class=\"GtkVBox\" id=\"vbox11\">\n            "
  "<property name=\"visible\">True</property>\n            <property name="
  "\"spacing\">4</property>\n            <child>\n              <widget cl"
  "ass=\"XfceHeading\" id=\"xfce-heading2\">\n                <property na"
  "me=\"visible\">True</property>\n                <property name=\"events"
  "\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_"
  "PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                <prope"
  "rty name=\"icon_name\">input-keyboard</property>\n                <prop"
  "erty name=\"title\" translatable=\"yes\">Add a new window-manage shortc"
  "ut theme</property>\n              </widget>\n              <packing>\n"
  "                <property name=\"expand\">False</property>\n           "
  "     <property name=\"fill\">False</property>\n              </packing>"
  "\n            </child>\n            <child>\n              <widget clas"
  "s=\"GtkLabel\" id=\"label32\">\n                <property name=\"visibl"
  "e\">True</property>\n                <property name=\"xalign\">0</prope"
  "rty>\n                <property name=\"label\" translatable=\"yes\">Typ"
  "e the name for the new shortcut theme:</property>\n              </widg"
  "et>\n              <packing>\n                <property name=\"expand\""
  ">False</property>\n                <property name=\"fill\">False</prope"
  "rty>\n                <property name=\"position\">1</property>\n       "
  "       </packing>\n            </child>\n            <child>\n         "
  "     <widget class=\"GtkAlignment\" id=\"alignment20\">\n              "
  "  <property name=\"visible\">True</property>\n                <property"
  " name=\"left_padding\">10</property>\n                <child>\n        "
  "          <widget class=\"GtkEntry\" id=\"add_keytheme_name_entry\">\n "
  "                   <property name=\"visible\">True</property>\n        "
  "            <property name=\"can_focus\">True</property>\n             "
  "     </widget>\n                </child>\n              </widget>\n    "
  "          <packing>\n                <property name=\"expand\">False</p"
  "roperty>\n                <property name=\"fill\">False</property>\n   "
  "             <property name=\"position\">2</property>\n              </"
  "packing>\n            </child>\n          </widget>\n          <packing"
  ">\n            <property name=\"expand\">False</property>\n            "
  "<property name=\"fill\">False</property>\n            <property name=\""
  "position\">1</property>\n          </packing>\n        </child>\n      "
  "  <child internal-child=\"action_area\">\n          <widget class=\"Gtk"
  "HButtonBox\" id=\"dialog-action_area2\">\n            <property name=\""
  "visible\">True</property>\n            <property name=\"layout_style\">"
  "GTK_BUTTONBOX_END</property>\n            <child>\n              <widge"
  "t class=\"GtkButton\" id=\"button2\">\n                <property name=\""
  "visible\">True</property>\n                <property name=\"can_focus\""
  ">True</property>\n                <property name=\"receives_default\">T"
  "rue</property>\n                <property name=\"label\" translatable=\""
  "yes\">gtk-cancel</property>\n                <property name=\"use_stock"
  "\">True</property>\n                <property name=\"response_id\">-6</"
  "property>\n              </widget>\n            </child>\n            <"
  "child>\n              <widget class=\"GtkButton\" id=\"button1\">\n    "
  "            <property name=\"visible\">True</property>\n               "
  " <property name=\"can_focus\">True</property>\n                <propert"
  "y name=\"receives_default\">True</property>\n                <property "
  "name=\"label\" translatable=\"yes\">gtk-ok</property>\n                "
  "<property name=\"use_stock\">True</property>\n                <property"
  " name=\"response_id\">-5</property>\n              </widget>\n         "
  "     <packing>\n                <property name=\"position\">1</property"
  ">\n              </packing>\n            </child>\n          </widget>\n"
  "          <packing>\n            <property name=\"expand\">False</prope"
  "rty>\n            <property name=\"pack_type\">GTK_PACK_END</property>\n"
  "          </packing>\n        </child>\n      </widget>\n    </child>\n"
  "  </widget>\n</glade-interface>\n"
};

static const unsigned xfwm4_dialog_glade_length = 81821u;

