/* automatically generated from xfwm4-workspace-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (workspace_dialog_glade)
#endif
#ifdef __GNUC__
static const char workspace_dialog_glade[] __attribute__ ((__aligned__ (4))) =
#else
static const char workspace_dialog_glade[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!DOCTYPE"
  " glade-interface SYSTEM \"glade-2.0.dtd\">\n<!--Generated with glade3 3"
  ".4.5 on Mon Jun 23 19:48:28 2008 -->\n<glade-interface>\n  <requires li"
  "b=\"xfce4\"/>\n  <widget class=\"GtkDialog\" id=\"main-dialog\">\n    <"
  "property name=\"border_width\">5</property>\n    <property name=\"windo"
  "w_position\">GTK_WIN_POS_CENTER_ON_PARENT</property>\n    <property nam"
  "e=\"type_hint\">GDK_WINDOW_TYPE_HINT_DIALOG</property>\n    <property n"
  "ame=\"has_separator\">False</property>\n    <child internal-child=\"vbo"
  "x\">\n      <widget class=\"GtkVBox\" id=\"main-vbox\">\n        <prope"
  "rty name=\"visible\">True</property>\n        <property name=\"spacing\""
  ">2</property>\n        <child>\n          <widget class=\"XfceHeading\""
  " id=\"xfce-heading1\">\n            <property name=\"visible\">True</pr"
  "operty>\n            <property name=\"icon_name\">xfce4-workspaces</pro"
  "perty>\n            <property name=\"title\" translatable=\"yes\">Works"
  "pace Settings</property>\n          </widget>\n          <packing>\n   "
  "         <property name=\"expand\">False</property>\n            <prope"
  "rty name=\"fill\">False</property>\n            <property name=\"positi"
  "on\">1</property>\n          </packing>\n        </child>\n        <chi"
  "ld>\n          <widget class=\"GtkVBox\" id=\"vbox1\">\n            <pr"
  "operty name=\"visible\">True</property>\n            <property name=\"s"
  "pacing\">5</property>\n            <child>\n              <widget class"
  "=\"GtkHBox\" id=\"hbox2\">\n                <property name=\"visible\">"
  "True</property>\n                <property name=\"spacing\">4</property"
  ">\n                <child>\n                  <widget class=\"GtkLabel\""
  " id=\"label1\">\n                    <property name=\"visible\">True</p"
  "roperty>\n                    <property name=\"label\" translatable=\"y"
  "es\">Number of workspaces:</property>\n                  </widget>\n   "
  "               <packing>\n                    <property name=\"expand\""
  ">False</property>\n                    <property name=\"fill\">False</p"
  "roperty>\n                  </packing>\n                </child>\n     "
  "           <child>\n                  <widget class=\"GtkSpinButton\" i"
  "d=\"workspace_count_spinbutton\">\n                    <property name=\""
  "visible\">True</property>\n                    <property name=\"can_foc"
  "us\">True</property>\n                    <property name=\"editable\">F"
  "alse</property>\n                    <property name=\"adjustment\">0 0 "
  "100 1 10 10</property>\n                  </widget>\n                  "
  "<packing>\n                    <property name=\"expand\">False</propert"
  "y>\n                    <property name=\"fill\">False</property>\n     "
  "               <property name=\"position\">1</property>\n              "
  "    </packing>\n                </child>\n              </widget>\n    "
  "          <packing>\n                <property name=\"expand\">False</p"
  "roperty>\n                <property name=\"fill\">False</property>\n   "
  "           </packing>\n            </child>\n            <child>\n     "
  "         <widget class=\"GtkTreeView\" id=\"treeview1\">\n             "
  "   <property name=\"visible\">True</property>\n                <propert"
  "y name=\"can_focus\">True</property>\n                <property name=\""
  "headers_clickable\">True</property>\n              </widget>\n         "
  "     <packing>\n                <property name=\"position\">1</property"
  ">\n              </packing>\n            </child>\n          </widget>\n"
  "          <packing>\n            <property name=\"position\">2</propert"
  "y>\n          </packing>\n        </child>\n        <child internal-chi"
  "ld=\"action_area\">\n          <widget class=\"GtkHButtonBox\" id=\"dia"
  "log-action_area1\">\n            <property name=\"visible\">True</prope"
  "rty>\n            <property name=\"layout_style\">GTK_BUTTONBOX_EDGE</p"
  "roperty>\n            <child>\n              <widget class=\"GtkButton\""
  " id=\"button2\">\n                <property name=\"visible\">True</prop"
  "erty>\n                <property name=\"can_focus\">True</property>\n  "
  "              <property name=\"receives_default\">True</property>\n    "
  "            <property name=\"label\" translatable=\"yes\">gtk-help</pro"
  "perty>\n                <property name=\"use_stock\">True</property>\n "
  "               <property name=\"response_id\">0</property>\n           "
  "   </widget>\n            </child>\n            <child>\n              "
  "<widget class=\"GtkButton\" id=\"button1\">\n                <property "
  "name=\"visible\">True</property>\n                <property name=\"can_"
  "focus\">True</property>\n                <property name=\"receives_defa"
  "ult\">True</property>\n                <property name=\"label\" transla"
  "table=\"yes\">gtk-close</property>\n                <property name=\"us"
  "e_stock\">True</property>\n                <property name=\"response_id"
  "\">0</property>\n              </widget>\n              <packing>\n    "
  "            <property name=\"position\">1</property>\n              </p"
  "acking>\n            </child>\n          </widget>\n          <packing>"
  "\n            <property name=\"expand\">False</property>\n            <"
  "property name=\"pack_type\">GTK_PACK_END</property>\n          </packin"
  "g>\n        </child>\n      </widget>\n    </child>\n  </widget>\n</gla"
  "de-interface>\n"
};

static const unsigned workspace_dialog_glade_length = 4991u;

